#!/bin/bash

source $(dirname "${BASH_SOURCE[0]}")/.abash/abash.sh

MODEL=$(fnfarg)
MODEL=${MODEL:-$OLLAMA_DEFAULT_MODEL}

[ -n "$MODEL" ] || die 'no model specified and OLLAMA_DEFAULT_MODEL is unset'

ARGS=()
arge think   && ARGS+=(--hidethinking) || ARGS+=(--think=false)
arge verbose && ARGS+=(--verbose)

exec ollama run "$MODEL" "${ARGS[@]}"
