#!/bin/bash

source $(dirname "${BASH_SOURCE[0]}")/.abash/abash.sh

MODEL=$(fnfarg)
MODEL=${MODEL:-$OLLAMA_DEFAULT_MODEL}

[ -n "$MODEL" ] || die 'no model specified and OLLAMA_DEFAULT_MODEL is unset'

ARGS=()
arge think   && ARGS+=(--hidethinking) || ARGS+=(--think=false)
arge verbose && ARGS+=(--verbose)

if arge edit; then
  TMP=$(mktemp --suffix=.md)
  trap 'rm -f "$TMP"' EXIT
  $EDITOR "$TMP"
  [ -s "$TMP" ] || exit 0

  exec ollama run "$MODEL" "${ARGS[@]}" < "$TMP"
fi

exec ollama run "$MODEL" "${ARGS[@]}"
