#!/bin/bash

set -euo pipefail

source "$(dirname "${BASH_SOURCE[0]}")"/.abash/abash.sh
sudo -v || exit 1

sigint

getPkgVer() {
  pacinfo "$1" 2> /dev/null | grep ^Version | awk '{ print $NF; }'
}

bannerline -f 'Updating packages'
pacman -Syu --noconfirm

if [ "$(getPkgVer local/nodejs)" != "$(getPkgVer community/nodejs)" ]; then
  echo
  bannerline -f 'Installing Node'
  # https://unix.stackexchange.com/questions/274727
  pacman -S community/nodejs --noconfirm --ask 4
fi

if pacman -Qdttq &> /dev/null; then
  bannerline 'Removing unrequired dependencies'
  pacman -Rsc $(pacman -Qdttq) --noconfirm
fi

bannerline 'Cleaning pacman cache'
if [ "$(printenv NO_PACMAN_CACHE)" == 1 ]; then
  sudo paccache -rk0 | awk NF
else
  sudo paccache -rk1 | awk NF
  sudo paccache -ruk0 | awk NF
fi

if cmd-exists pnpm; then
  bannerline 'Updating Node modules'
  pnpm -g update
fi
