#!/bin/bash

set -euo pipefail

source "$(dirname "${BASH_SOURCE[0]}")"/.abash/abash.sh
sudo -v || exit 1

sigint

bannerline -f 'Updating packages'
pacman -Syu --noconfirm

if pacman -Qdttq &> /dev/null; then
  bannerline 'Removing unrequired dependencies'
  pacman -Rsc $(pacman -Qdttq) --noconfirm
fi

bannerline 'Cleaning pacman cache'
if [ "$(printenv NO_PACMAN_CACHE)" == 1 ]; then
  sudo paccache -rk0 | awk NF
else
  sudo paccache -rk1 | awk NF
  sudo paccache -ruk0 | awk NF
fi

if cmd-exists pnpm; then
  bannerline 'Updating Node modules'
  pnpm -g update
fi

if cmd-exists pip-update; then
  bannerline 'Updating Python modules'
  pip-update
fi
