#!/bin/bash
#
# Name: archkeys
# Auth: Gavin Lloyd <gavinhungry@gmail.com>
# Date: 30 Mar 2012 (last modified: 13 Aug 2012)
# Desc: Updates/fetches the Arch Linux Developer/TU package-signing keys
#

source functions.sh

die "use pacman-key --refresh-keys"

ARCH_DEVS_PAGE='https://www.archlinux.org/developers/'
ARCH_TU_PAGE='https://www.archlinux.org/trustedusers/'
KEYSERVER='pgp.mit.edu:11371/pks/lookup?'

sudo -v

keys () {
  echo $(curl -s ${1} | grep ${KEYSERVER} | sed 's/<[^>]*>//g' |\
         sed -e 's/^.*\(0x.[A-Z0-9]\{7\}\).*$/\1/')
}

msg "Checking DEV keys"
ARCH_DEV_KEYS=$(keys ${ARCH_DEVS_PAGE})
for KEY in ${ARCH_DEV_KEYS}; do
  msg "DEV key ${KEY}"
  sudo pacman-key --recv-keys ${KEY}
done

msg "Checking TU keys"
ARCH_TU_KEYS=$(keys ${ARCH_TU_PAGE})
for KEY in ${ARCH_TU_KEYS}; do
  msg "TU key ${KEY}"
  sudo pacman-key --recv-keys ${KEY}
done
