#!/bin/bash

set -euo pipefail

source "$(dirname "${BASH_SOURCE[0]}")"/abash/abash.sh
sudo -v || exit 1

sigint

bannerline -f 'Updating pacman databases'
packer -Syy

bannerline 'Updating packages'
packer -Sua --noconfirm
packer -Qdtq &> /dev/null && packer -Rsc $(packer -Qdtq) --noconfirm

bannerline 'Cleaning pacman cache'
PACCACHE_ARGS=(-rk0)
[ "$(printenv NO_PACMAN_CACHE)" == 1 ] || PACCACHE_ARGS+=(-u)
sudo /usr/bin/paccache "${PACCACHE_ARGS[@]}" 2> /dev/null

if [ -x /usr/bin/npm ]; then
  bannerline 'Updating global Node modules'
  npm -g soft-update
fi
