#!/bin/bash

set -eo pipefail
source "$(dirname "${BASH_SOURCE[0]}")"/.abash/abash.sh

sudo -v || exit 1

sigint

getPkgVer() {
  pacinfo "$1" 2> /dev/null | grep ^Version | awk '{ print $NF; }'
}

bannerline -f 'Updating packages'
pacman -Syu --noconfirm

if pacman -Qdttq &> /dev/null; then
  bannerline 'Removing unrequired dependencies'
  pacman -Rsc $(pacman -Qdttq) --noconfirm
fi

bannerline 'Cleaning pacman cache'
if [ "$(printenv NO_PACMAN_CACHE)" == 1 ]; then
  sudo paccache -rk0 | awk NF
else
  sudo paccache -rk1 | awk NF
  sudo paccache -ruk0 | awk NF
fi
