#!/bin/bash

source $(dirname "${BASH_SOURCE[0]}")/abash/abash.sh
[ $# -eq 1 ] || usage 'MAC_ADDRESS'

is_mac() {
  [[ "$1" =~ ^([0-9a-fA-F]{2}[:-]?){6}$ ]]
}

format_mac() {
  is_mac "$1" && echo -n "$1" | tr -d :- | fold -w2 | tr '\n' : | tr [A-Z] [a-z]
}

MAC=$(format_mac $1) || die 'invalid MAC address'

set -o pipefail

(arp -an | grep -i $MAC | awk -F '[()]' '{ print $2 }') || \
(arp-scan --localnet --ignoredups | grep -i $MAC | awk '{ print $1 }')
