#!/bin/bash

MAX_LENGTH=${1:-80}
DELIMITER=•
  
TITLE=
while IFS= read -r LINE; do
  LINE=$(echo $LINE | sed 's/ [[(][^])[(]*[])]//g')
  [ ${#LINE} -eq 0 ] && continue
  TITLE+="$LINE $DELIMITER "
done <<< $(
  castd-cmd metadata ||
  yt-music-title ||
  plex-music-title ||
  rhythmbox-title
)

TITLE=${TITLE% $DELIMITER }

if [ -z "$TITLE" ]; then
  [ "$(ps -o comm= $PPID)" == 'wrapper-2.0' ] && echo ' ' # xfce4-panel
  exit 1
fi

[ $MAX_LENGTH -gt 0 -a ${#TITLE} -gt $MAX_LENGTH ] && TITLE="${TITLE::$MAX_LENGTH} ..."

echo -en "🎵 ${TITLE}\n"
