#!/bin/bash

source $(dirname "${BASH_SOURCE[0]}")/.abash/abash.sh

MAX_LENGTH=$(arg max-length 0)
LABEL=$(arg label)
DELIMITER=$(arg delimiter -)
  
TITLE=
while IFS= read -r LINE; do
  LINE=$(echo $LINE | sed 's/ [[(][^])[(]*[])]//g')
  [ ${#LINE} -eq 0 ] && continue
  TITLE+="$LINE $DELIMITER "
done <<< $(castctl-title || yt-music-title || rhythmbox-title)
TITLE=${TITLE% $DELIMITER }

if [ -z "$TITLE" ]; then
  arge zwsp && echo -n "​" # zero-width space for Xfce genmon
  exit 1
fi

[ $MAX_LENGTH -gt 0 -a ${#TITLE} -gt $MAX_LENGTH ] && TITLE="${TITLE::$MAX_LENGTH} ..."
[ -n "$LABEL" ] && echo -n "$LABEL "

echo $TITLE
