#!/bin/bash

set -eo pipefail
source $(dirname "${BASH_SOURCE[0]}")/.abash/abash.sh

DEVICE=$(arg device BAT0)
DEVICE_PATH="/sys/class/power_supply/${DEVICE}"

DEVICE_NAME=$(cat ${DEVICE_PATH}/model_name)
DEVICE_STATUS=$(cat ${DEVICE_PATH}/status)
DEVICE_CAPACITY=$(cat ${DEVICE_PATH}/capacity)
NOTIFY_CAPACITY=$(arg notify 20)

ARGS=""
arge wait && ARGS+="--wait"

if [ \
  "$DEVICE_STATUS" == 'Discharging' \
  -a $DEVICE_CAPACITY -le $NOTIFY_CAPACITY \
  -a $DEVICE_CAPACITY -ne 0 \
]; then
  notify-send $ARGS -u critical -t 0 \
    "${DEVICE_NAME} battery low" \
    "Battery level is ${DEVICE_CAPACITY}%"
fi
