#!/bin/bash
#
# Name: bssid
# Auth: Gavin Lloyd
# Desc: Locks wireless BSSID to current AP in Network Manager
#

source $(dirname "${BASH_SOURCE}")/abash/abash.sh

NM_DIR=/etc/NetworkManager/system-connections

CURRENT=$(nm-tool | grep \ \\*)
ESSID=$(echo "${CURRENT}" | sed -e 's/.*\*\([^:]*\):.*/\1/')
BSSID=$(echo "${CURRENT}" | sed -e 's/.*\(\([A-F0-9]\{2\}:\?\)\{6\}\).*/\1/i' \
                          | tr '[A-F]' '[a-f]' | sed 's/00/0/g')

[ ! -z "$2" ] && ESSID="$2"
[ -z "${ESSID}" ] && die "couldn't get current ESSID!"
[ ! -f "${NM_DIR}/${ESSID}" ] && die "no profile '${ESSID}' found"

# remove old BSSID
unlock() {
  sudo sed -i -e 's/^bssid=.*$//g' "${NM_DIR}/${ESSID}"
  status
}

# place new BSSID
lock() {
  sudo sed -i -e "s/^\(\[802-11-wireless\]\)/\1\nbssid=${BSSID}/" "${NM_DIR}/${ESSID}"
  status
}

status() {
  BSSID_REAL=$(sudo grep '^bssid=' "${NM_DIR}/${ESSID}" | cut -d'=' -f2 | \
               tr '[a-f]' '[A-F'] | sed -e 's/\(^\|:\)0\(:\|$\)/\100\2/g')
  if [ -z ${BSSID_REAL} ]; then
    msg "'${ESSID}' BSSID unlocked"
  else
    msg "'${ESSID}' BSSID locked to ${BSSID_REAL}"
  fi
}

case "$1" in
  'lock') unlock; lock ;;
  'unlock') unlock ;;
  'status') status ;;
  *) usage "lock|unlock|status"
esac
