#!/bin/bash

source $(dirname "${BASH_SOURCE[0]}")/.abash/abash.sh

PIPX_VENV_PYTHON=~/.local/share/pipx/venvs/cast-control/bin/python

eval '$HOME/bin/castctl connect --name "$CASTCTL_NAME" --log-level INFO' 2>&1 |
while read -r LINE; do
  echo $LINE
  [ "$LINE" = "AssertionError" ] && kill $(pidof $PIPX_VENV_PYTHON)
done
