#!/bin/bash

STATUS=$(playerctl-castctl status)
[ "$STATUS" == 'Playing' ] || exit 1

ARTIST_FIELD=artist
GENRE=$(playerctl-castctl metadata -f "{{xesam:genre}}")
[ "$GENRE" == 'Podcast' ] && ARTIST_FIELD=album

ARTIST=$(playerctl-castctl metadata -f "{{xesam:${ARTIST_FIELD}}}")
TITLE=$(playerctl-castctl metadata -f "{{xesam:title}}")

echo $ARTIST
echo $TITLE
