#!/bin/bash

HOST=$(echo $1 | cut -d':' -f1)
PORT=$(echo $1 | cut -d':' -s -f2)

echo | openssl s_client -connect $HOST:${PORT:-443} 2> /dev/null | sed -ne '/--BEGIN CERTIFICATE--/,/--END CERTIFICATE--/p'
