#!/bin/bash

USER_AGENT=$(node -p << EOF
  let ua = require('random-useragent').getRandom(ua => {
    return !ua.deviceType && ['Firefox', 'Chrome'].includes(ua.browserName);
  });

  if (ua) {
    console.log(ua);
  }

  process.exit();
EOF
)

[ $? -eq 0 -a -n "$USER_AGENT" ] || exit 1
echo "USER_AGENT: $USER_AGENT"

DATA_DIR="${HOME}/.cache/chromium-tor.$$${RANDOM}" # mounted in tmpfs
mkdir -pm0700 "${DATA_DIR}/Default"

cat > "${DATA_DIR}/Default/Preferences" << EOF
{
  "browser": {
    "custom_chrome_frame": false,
    "default_browser_infobar_last_declined": "1",
    "default_browser_setting_enabled": false
  },

  "bookmark_bar": {
    "show_on_all_tabs": true
  },

  "default_search_provider_data": {
    "template_url_data": {
      "id": "0",
      "keyword": "ddg",
      "short_name": "DuckDuckGo",
      "url": "https://duckduckgo.com/?q={searchTerms}"
    }
  }
}
EOF

chromium \
  --user-data-dir="$DATA_DIR" \
  --incognito \
  --no-pings \
  --no-first-run \
  --window-size=1920,1200 \
  --proxy-server=socks5://127.0.0.1:9050 \
  --user-agent="$USER_AGENT" \
  'https://check.torproject.org'

rm -fr "$DATA_DIR"
