#!/bin/bash

FILE=$1
ARGS=""

if [ -z "$FILE" ]; then
  exec xclip -selection clipboard
fi

MIME=$(mime "$FILE")

if [[ "$MIME" == image/* ]]; then
  ARGS+="-t $MIME"
fi

exec xclip $ARGS -selection clipboard "$FILE"
