#!/bin/bash

NAME=${1:-Package}

LABELS=$(find /sys/devices/platform/coretemp.* -name temp*_label)
[ -n "$LABELS" ] || exit 2

LABEL=$(grep -l "$NAME" $LABELS | head -n1)
[ -e "$LABEL" ] || exit 3

INPUT=${LABEL%_label}_input
TEMP=$(echo "scale=0; $(cat $INPUT) / 1000" | bc)
echo "${TEMP}°C"
