#!/bin/bash

clean() {
  tr -s " " | cut -d":" -f2- | cut -d@ -f1 | xargs
}

IFS=$(echo -en "\n\b")
CPU=$(grep '^model name' /proc/cpuinfo | uniq | clean)
if [ -z "$CPU" ]; then
  CPU=$(grep '^cpu model' /proc/cpuinfo | uniq | clean)
fi

SOCKETS=$(lscpu | grep ^'NUMA node(s):' | clean)
THREADS=$(lscpu | grep ^'CPU(s):' | clean)

CPU_LABEL=$(echo "${CPU}" \
  | sed -r 's/\((R|TM)\)//g' \
  | sed -r 's/\sCPU\s/ /g' \
  | sed -r 's/\s[0-9]+-Core Processor$//g'
)

if [ -z "$CPU_LABEL" ]; then
  LSCPU=$(lscpu)

  CPU_LABEL=$(echo "$LSCPU" | grep -m1 ^'Vendor ID:' | clean)
  CPU_LABEL+=' '
  CPU_LABEL+=$(echo "$LSCPU" | grep -m1 ^'Model name:' | clean)
fi

OUTPUT=""
[ "${SOCKETS:-1}" -ne 1 ] && OUTPUT+="$SOCKETS x "
OUTPUT+="$CPU_LABEL ($THREADS)"
echo $OUTPUT
