#!/bin/bash

clean() {
  tr -s " " | cut -d":" -f2- | xargs
}

IFS=$(echo -en "\n\b")
CPU=$(grep '^model name' /proc/cpuinfo | uniq | clean)
SOCKETS=$(lscpu | grep ^'NUMA node(s):' | clean)
THREADS=$(lscpu | grep ^'CPU(s):' | clean)

CLEANCPU=$(echo "${CPU}" | sed -r 's/\((R|TM)\)//g' | sed -r 's/\sCPU\s/ /g')

OUTPUT=""
[ "${SOCKETS:-1}" -ne 1 ] && OUTPUT+="$SOCKETS x "
OUTPUT+="$CLEANCPU [$THREADS]"
echo $OUTPUT
