#!/bin/bash

set -eo pipefail
source $(dirname "${BASH_SOURCE[0]}")/.abash/abash.sh

K10TEMP_NAME=$(grep -l ^k10temp$ /sys/class/hwmon/hwmon*/name)
K10TEMP_DIR=$(dirname "$K10TEMP_NAME")

TCTL=$(grep -l ^Tctl$ $K10TEMP_DIR/temp*_label)
TCTL_VAL=$(cat "${TCTL%_*}_input")

if arge raw; then
  echo $TCTL_VAL
  exit
fi

printf "%.0f°C\n" "$(echo "$TCTL_VAL / 1000" | bc -l)"
