#!/bin/bash

source $(dirname "${BASH_SOURCE[0]}")/.abash/abash.sh

arge ccd &&
  TEMP_CMD=ccd-temp ||
  TEMP_CMD=cpu-temp

OUTPUT="$(cpu-util || echo ?) • $($TEMP_CMD || echo ?)"
OUTPUT=$(enpad "$OUTPUT" $(arg padding 0))

echo "$OUTPUT"
