#!/bin/bash

source $(dirname "${BASH_SOURCE[0]}")/.abash/abash.sh
DELIMITER=$(arg delimiter /)
OUTPUT="$(cpu-util || echo ?) $DELIMITER $(cpu-temp $(pfarg core) || echo ?)"

if arge ibm-fan; then
  OUTPUT+=" $DELIMITER $(ibm-fan)"
fi

echo $OUTPUT
