#!/bin/bash

set -eo pipefail
source $(dirname "${BASH_SOURCE[0]}")/.abash/abash.sh

HWMON_NAME_PATH=$(grep -l "^${HWMON_CPU_TEMP_NAME}$" /sys/class/hwmon/hwmon*/name)
HWMON_DIR=$(dirname "$HWMON_NAME_PATH")

TCTL=$(grep -l ^Tctl$ $HWMON_DIR/temp*_label 2> /dev/null || true)
TCTL=${TCTL:-$HWMON_DIR/temp1}
TCTL_VAL=$(cat "${TCTL%_*}_input")

if arge raw; then
  echo $TCTL_VAL
  exit
fi

printf "%.0f°C\n" "$(echo "$TCTL_VAL / 1000" | bc -l)"
