#!/bin/bash

source $(dirname "${BASH_SOURCE[0]}")/.abash/abash.sh
DELIMITER=$(arg delimiter /)
TEMP_ARGS=
if arge core; then
  TEMP_ARGS+=' --core'
fi

OUTPUT="$(cpu-util || echo ?) $DELIMITER $(cpu-temp $TEMP_ARGS || echo ?)"

if arge ibm-fan; then
  OUTPUT+=" $DELIMITER $(ibm-fan --speed $(arg ibm-fan))"
fi

echo $OUTPUT
