#!/usr/bin/env node

const cronstrue = require('cronstrue');

let cron;
if (process.argv[2]) {
  cron = process.argv[2].trim().replace(/\s+/g, ' ');
}

try {
  console.log(cronstrue.toString(cron));
} catch(err) {
  console.error(err);
  process.exit(1);
}
