#!/bin/bash

for DIR in /proc/*/; do
  [ ! -e $DIR/comm ] && continue

  COMM=$(cat $DIR/comm)
  [ -z "$COMM" ] && continue

  DELETED="$COMM (deleted)"
  EXE=$(basename "$(readlink -q $DIR/exe)")
  LINK=$(basename "$(readlink -q $(which $COMM 2> /dev/null) 2> /dev/null)")

  [ "$EXE" == "$COMM (deleted)" -o "$EXE" == "$LINK (deleted)" ] && echo $COMM
done
