#!/usr/bin/env python

import warnings
warnings.filterwarnings('ignore')

import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk

import psutil
import subprocess
import threading
import sys

APP_NAME = 'Discord'
APP_PATH = '/opt/discord/Discord'
ICON_NAME = 'discord-tray'

#
def is_running(exe):
  for proc in psutil.process_iter():
    try:
     if (proc.exe() == exe):
        return True
    except:
      continue

  return False

#
def open_app():
  return subprocess.Popen(APP_PATH)

#
def start_app():
  global process
  process = open_app()
  process.wait()
  quit()

#
def quit_app(menuitem):
  process.terminate()
  Gtk.main_quit()

#
def on_click(icon):
  open_app()

#
def on_context(icon, button, time):
  quit = Gtk.MenuItem()
  quit.set_label('Quit ' + APP_NAME)
  quit.connect('activate', quit_app)

  menu = Gtk.Menu()
  menu.append(quit)
  menu.show_all()

  menu.popup(None, None, None, Gtk.StatusIcon.position_menu, button, time)

# ------------------------------------------------------------------------------

if is_running(APP_PATH):
  open_app()
  sys.exit()

icon = Gtk.StatusIcon()
icon.set_tooltip_text(APP_NAME)
icon.set_from_icon_name(ICON_NAME)
icon.connect('activate', on_click)
icon.connect('popup-menu', on_context)

thread = threading.Thread(target=start_app)
thread.start()

Gtk.main()
