#!/bin/bash

for DISK in $(lsblk -rndA --sort name | awk '{ print $1 }'); do
  REMOVABLE=$(cat /sys/class/block/$DISK/removable)
  [ "$REMOVABLE" == 1 ] && continue

  VENDOR=$(cat /sys/class/block/$DISK/device/vendor 2> /dev/null | xargs)
  MODEL=$(cat /sys/class/block/$DISK/device/model 2> /dev/null | xargs)
  [ "$MODEL" == 'MassStorageClass' ] && continue

  [ -z "$MODEL" ] && continue
  [ -n "$VENDOR" -a "$VENDOR" != "ATA" ] && echo -n "$VENDOR "
  echo "$MODEL"
done
