#!/bin/bash

PKNAME=$(lsblk -no PKNAME $(findmnt -n -o SOURCE /) 2> /dev/null)
if [[ "$PKNAME" == mmcblk* ]]; then
  MMC_CID=$(mmc cid read "/sys/block/$PKNAME/device" 2> /dev/null)

  VENDOR=$(echo "$MMC_CID" | awk -F"'" '/^manufacturer:/ { print $2 }')
  MODEL=$(echo "$MMC_CID" | awk -F"'" '/^product:/ { print $2 }')

  echo "$VENDOR $MODEL"
fi

for DISK in $(lsblk -rndA --sort name | awk '{ print $1 }'); do
  REMOVABLE=$(cat /sys/class/block/$DISK/removable)
  [ "$REMOVABLE" == 1 ] && continue

  VENDOR=$(cat /sys/class/block/$DISK/device/vendor 2> /dev/null | xargs)
  MODEL=$(cat /sys/class/block/$DISK/device/model 2> /dev/null | xargs)
  [ "$MODEL" == 'MassStorageClass' ] && continue

  if [ ! -z "$MODEL" -a "$VENDOR $MODEL" != 'SYNOLOGY Storage' ]; then
    [ -n "$VENDOR" -a "$VENDOR" != "ATA" ] && echo -n "$VENDOR "
    echo "$MODEL"
    continue
  fi

  # Virtio
  PCI=$(readlink -f /sys/class/block/$DISK/device \
    | grep -oP '[\da-f]{4}:[\da-f]{2}:[\da-f]{2}\.[\da-f]' \
    | tail -1)
  [ -z "$PCI" ] && continue

  MODEL=$(lspci -s "$PCI" -mm \
    | grep -oP '"[^"]*"' \
    | tr -d '"' \
    | sed 's/\s*\[[a-f0-9]*\]$//g' \
    | sed -n '3p' \
    | paste -sd' ')
  [[ "$MODEL" != *Virtio* ]] && continue

  SIZE_GB=$(( $(cat /sys/class/block/$DISK/size) * 512 / 1024 / 1024 / 1024 ))

  [[ "$VENDOR" != 0x* ]] && echo -n "$VENDOR "
  echo "$MODEL ${SIZE_GB} GiB"
done
