#!/bin/bash

source $(dirname "${BASH_SOURCE}")/abash/abash.sh
DOMAIN=$(fnfarg)
[ -n "$DOMAIN" ] || usage '[-4|-6] DOMAIN'

set -o pipefail

KEY=ahosts
arge 4 && KEY=ahostsv4
arge 6 && KEY=ahostsv6

getent "$KEY" "$DOMAIN" | awk '{ print $1; }' | uniq
