#!/bin/bash
#
# Name: edit
# Auth: Gavin Lloyd <gavinhungry@gmail.com>
# Desc: Opens a file for editing
#

source $(dirname "${BASH_SOURCE}")/abash/abash.sh

if [ $# -eq 0 ]; then
  die "no file(s) specified"
fi

for FILE in "$@"; do

  if [ ! -e "$FILE" ]; then
    msg "'$FILE' does not exist"
    continue
  elif [ ! -r "$FILE" ]; then
    msg "no permission to read '$FILE'"
    continue
  fi

  if [[ $TERM == xterm* ]] || [ $TERM = "screen" ]; then
    ${EDITOR_X11:-subl} "$FILE" &> /dev/null &
  else
    ${EDITOR:-emacs} "$FILE"
  fi
done
