#!/bin/bash

source $(dirname "${BASH_SOURCE}")/abash/abash.sh
[ $# -ge 1 ] || usage 'FILE [FILE ...]'

for ARG in "$@"; do

  if [ ! -e "$ARG" ]; then
    warn "$ARG does not exist"
    continue
  fi

  if [ ! -r "$ARG" ]; then
    warn "$ARG is not readable"
    continue
  fi

  if [[ $TERM == xterm* ]] || [ $TERM = 'screen' ]; then
    ${EDITOR_X11:-subl} "$ARG" &> /dev/null &
  else
    ${EDITOR:-emacs} "$ARG"
  fi
done
