#!/bin/bash

source $(dirname "${BASH_SOURCE[0]}")/.abash/abash.sh

MAN=/usr/bin/man
export GROFF_NO_SGR=1

[ $# -gt 0 ] || exec $MAN
istty || exec $MAN "$@"
$MAN -w "$@" > /dev/null || exit $?

exec emacs --eval "
  (progn
    (man \"$*\")
    (delete-window)
    (local-set-key (kbd \"q\") 'save-buffers-kill-emacs)
    (local-set-key (kbd \"/\") 'isearch-forward)
    (local-set-key (kbd \",\") 'isearch-repeat-backward)
    (local-set-key (kbd \".\") 'isearch-repeat-forward)
    (local-set-key (kbd \"<down>\") 'scroll-up-line)
    (local-set-key (kbd \"<up>\") 'scroll-down-line)
    (local-unset-key [?\r])
    (setq lazy-highlight-buffer t)
    (setq lazy-highlight-cleanup nil)
    (setq line-timer (run-with-timer 0 0.001 'display-line-numbers-update))
    (run-with-timer 1 nil 'cancel-timer line-timer)
  )"
