#!/bin/bash

source $(dirname "${BASH_SOURCE[0]}")/.abash/abash.sh

echo

STR=$(hostname)
if [ -n "$STR" ]; then
  color bold white
  echo -n '   HOST'
  color end
  echo -n ': '
  echo "$STR"
fi

STR=$(grep ^PRETTY_NAME= /etc/os-release 2> /dev/null | cut -d'"' -f2)
if [ -n "$STR" ]; then
  color bold black
  echo -n '     OS'
  color end
  echo -n ': '
  echo "$STR"
fi

STR=$(uname -srm)
if [ -n "$STR" ]; then
  color bold black
  echo -n ' KERNEL'
  color end
  echo -n ': '
  echo "$STR"
fi

STR=$(model)
if [ -n "$STR" ]; then
  color bold cyan
  echo -n '  MODEL'
  color end
  echo -n ': '
  echo "$STR"
fi

STR=$(cpu)
if [ -n "$STR" ]; then
  color bold blue
  echo -n '    CPU'
  color end
  echo -n ': '
  echo "$STR"
fi

STR=$(gpu)
if [ -n "$STR" ]; then
  color bold green
  echo -n '    GPU'
  color end
  echo -n ': '
  echo "$STR" | njoin ', '
fi

STR=$(mem)
if [ -n "$STR" ]; then
  color bold magenta
  echo -n '    MEM'
  color end
  echo -n ': '
  echo "$STR"
fi

STR=$(disk)
if [ -n "$STR" ]; then
  color bold yellow
  echo -n '   DISK'
  color end
  echo -n ': '
  echo "$STR" | njoin ', '
fi

STR=$(bios)
if [ -n "$STR" ]; then
  color bold red
  echo -n '   BIOS'
  color end
  echo -n ': '
  echo "$STR"
fi

STR=$(ucode)
if [ -n "$STR" ]; then
  color bold red
  echo -n '  UCODE'
  color end
  echo -n ': '
  echo "$STR"
fi

echo
