#!/bin/bash

source $(dirname "${BASH_SOURCE[0]}")/.abash/abash.sh

echo

STR=$(hostname -f)
if [ -n "$STR" ]; then
  color bold black
  echo -n '   HOST'
  color end
  echo -n ': '
  echo "$STR"
fi

STR=$(cpu)
if [ -n "$STR" ]; then
  color bold blue
  echo -n '    CPU'
  color end
  echo -n ': '
  echo "$STR"
fi

STR=$(gpu)
if [ -n "$STR" ]; then
  color bold green
  echo -n '    GPU'
  color end
  echo -n ': '
  echo "$STR"
fi

STR=$(mem)
if [ -n "$STR" ]; then
  color bold magenta
  echo -n '    MEM'
  color end
  echo -n ': '
  echo "$STR"
fi

STR=$(disk)
if [ -n "$STR" ]; then
  color bold yellow
  echo -n '   DISK'
  color end
  echo -n ': '
  echo "$STR" | sed ':a;N;$!ba;s/\n/, /g'
fi

STR=$(model)
if [ -n "$STR" ]; then
  color bold cyan
  echo -n '  MODEL'
  color end
  echo -n ': '
  echo "$STR"
fi

STR=$(bios)
if [ -n "$STR" ]; then
  color bold cyan
  echo -n '   BIOS'
  color end
  echo -n ': '
  echo "$STR"
fi

STR=$(ucode)
if [ -n "$STR" ]; then
  color bold red
  echo -n '  UCODE'
  color end
  echo -n ': '
  echo "$STR"
fi

echo
