#!/bin/bash

source $(dirname "${BASH_SOURCE[0]}")/.abash/abash.sh

echo

STR=$(grep ^PRETTY_HOSTNAME= /etc/machine-info 2> /dev/null | cut -d= -f2)
if [ -z "$STR" ]; then
  STR=$(hostname)
  STR="${STR^}"
fi

if [ -n "$STR" ]; then
  color bold white
  echo -n '   HOST'
  color end
  echo -n ': '
  echo "$STR"
fi

STR=$(grep ^PRETTY_NAME= /etc/os-release 2> /dev/null | cut -d'"' -f2)
if [ -n "$STR" ]; then
  color bold black
  echo -n '     OS'
  color end
  echo -n ': '
  echo "$STR"
fi

STR=$(uname -srm)
if [ -n "$STR" ]; then
  color bold black
  echo -n ' KERNEL'
  color end
  echo -n ': '
  echo "$STR"
fi

STR=$(cpu)
if [ -n "$STR" ]; then
  color bold purple
  echo -n '    CPU'
  color end
  echo -n ': '
  echo "$STR"
fi

STR=$(mem)
if [ -n "$STR" ]; then
  color bold yellow
  echo -n '    MEM'
  color end
  echo -n ': '
  echo "$STR"
fi

STR=$(gpu)
if [ -n "$STR" ]; then
  color bold green
  echo -n '    GPU'
  color end
  echo -n ': '
  echo "$STR" | njoin ', '
fi

STR=$(disk)
if [ -n "$STR" ]; then
  echo "$STR" | while IFS= read -r DISK; do
    color bold cyan
    echo -n '   DISK'
    color end
    echo -n ': '
    echo "$DISK"
  done
fi

STR=$(model)
if [ -n "$STR" ]; then
  color bold blue
  echo -n '  MODEL'
  color end
  echo -n ': '
  echo "$STR"
fi

STR=$(bios)
if [ -n "$STR" ]; then
  color bold red
  echo -n '   BIOS'
  color end
  echo -n ': '
  echo "$STR"
fi

STR=$(ucode)
if [ -n "$STR" ]; then
  color bold red
  echo -n '  UCODE'
  color end
  echo -n ': '
  echo "$STR"
fi

echo
