#!/bin/bash

case "$2" in
  name) F=1 ;;
  office) F=2 ;;
  phone) F=3 ;;
  contact|email) F=4 ;;
esac

/usr/bin/grep ^${1:-$(whoami)}: /etc/passwd | /usr/bin/cut -d':' -f5 | /usr/bin/cut -d',' -f${F:-1}
