#!/bin/bash

source $(dirname "${BASH_SOURCE[0]}")/.abash/abash.sh

entity() { sed 's/&/&amp;/g' ;}

COMMAND=$(arg command)
TOOLTIP=$(arg tooltip)

TXT=$(${COMMAND} | entity)
TOOL=$(${TOOLTIP} | entity)

cat <<EOF
<txt>${TXT:- }</txt>
<tool>$TOOL</tool>
EOF
