#!/bin/bash

source $(dirname "${BASH_SOURCE[0]}")/.abash/abash.sh

entity() { sed 's/&/&amp;/g' ;}

COMMAND=$(arg command)
TOOLTIP=$(arg tooltip)
PREFIX=$(arg prefix)

TXT=$(${COMMAND} | entity)
TOOL=$(${TOOLTIP} | entity)

[ -n "$PREFIX" -a -n "$TXT" ] && TXT="$PREFIX $TXT"

# some genmon instances are only visible some of the time, add in-string padding
if arge padded && [ -n "$TXT" ]; then
  PADDING=$(printf "%5s" '')
  TXT=" ${TXT}${PADDING}"
fi

# xfce4-panel can render a thin gap artifact if stdout is empty (even with ZWSP)
THSP=$'\u2009'

cat <<EOF
<txt>${TXT:-$THSP}</txt>
<tool>$TOOL</tool>
EOF
