#!/bin/bash

set -eo pipefail
source $(dirname "${BASH_SOURCE[0]}")/.abash/abash.sh

[ -n "$1" ] || usage 'FILE [--fps FRAMERATE] [--width WIDTH]'
[ -f "$1" ] || die "$1 does not exist"

set -e

FPS=$(arg fps 24)
WIDTH=$(arg width 480)

TMP=$(tmpdir)
PALETTE=$TMP/palette-$1-$$.png

ffpb -i "$1" -vf fps=$FPS,palettegen "$PALETTE"
ffpb -threads 0 -i "$1" -i "$PALETTE" -filter_complex \
  "fps=$FPS,scale=$WIDTH:-1:flags=lanczos[x];[x][1:v]paletteuse" \
  "${1%.*}.gif"

tmpdirclean
