#!/bin/bash

BASE_URL=$(git remote get-url origin | sed 's/^github:/https:\/\/github.com\//')
[ -n "$BASE_URL" ] || exit 1

open_page() {
  PAGE_NAME=$1
  [ -n "$3" ] && PAGE_NAME=$2

  URL=$(echo "${BASE_URL}/$PAGE_NAME/$3" | sed 's/\/*$//')
  $BROWSER "$URL" & &> /dev/null
  exit
}

case $1 in
  c|commit|commits)    open_page commits commit $2 ;;
  i|issue|issues)      open_page issues issues $2 ;;
  p|pull|pulls|pr|prs) open_page pulls pull $2 ;;
  a|actions|ci)        open_page actions ;;
  s|settings)          open_page settings ;;
  *)
    BRANCH=$(git br)
    if [ -n "$BRANCH" -a "$BRANCH" != "main" -a "$BRANCH" != "master" ]; then
      open_page tree/$BRANCH
    fi

    open_page
  ;;
esac
