#!/bin/bash
#
# Name: glock
# Auth: Gavin Lloyd
# Date: 13 Jan 2011 (last modified 05 Aug 2014)
# Desc: Locks console with physlock if not already locked
#

DOCK=/usr/bin/dock
DISP=/usr/bin/display
LOCK=/usr/bin/physlock

[ ! -z $1 ] && USERNAME=$1 || USERNAME=$(whoami)
[ -z "$USERNAME" -o "$USERNAME" == 'root' ] && USERNAME=gavin

if !(/bin/pidof $LOCK &> /dev/null); then
  [ -x $DISP ] && $DISP single
  $LOCK -s -u $USERNAME
  [ -x $DOCK ] && $DOCK
fi
