#!/bin/bash
#
# Name: glock
# Auth: Gavin Lloyd
# Date: 13 Jan 2011 (last modified 05 Aug 2014)
# Desc: Locks console with physlock if not already locked
#

DOCK=/usr/bin/dock
DISPLAY=/usr/bin/display
PHYSLOCK=/usr/bin/physlock

[ ! -z $1 ] && USER=$1 || USER=$(whoami)
[ -z ${USER} -o ${USER} == 'root' ] && USER=gavin

if !(/bin/pidof ${PHYSLOCK} &> /dev/null); then
  ${DISPLAY} single
  ${PHYSLOCK} -s -u ${USER}
  ${DOCK} check && ${DISPLAY} dock
fi
