#!/bin/bash

for IF in $(ip -o link | awk -F': ' '{ print $2 }'); do
  IF_SPEED=$(ethtool $IF 2> /dev/null | awk '/Speed:/ { print $2 }')
  [ -n "$IF_SPEED" -a "$IF_SPEED" != 'Unknown!' ] && echo "${IF}: ${IF_SPEED}"
done
