#!/usr/bin/env node

var fs = require('fs');
var imgur = require('imgur');

var file = process.argv[2];

if (!file) {
  console.error('Usage: imgur [IMAGE]');
  process.exit(1);
}

if (!fs.existsSync(file)) {
  console.error('File does not exist.');
  process.exit(2);
}

imgur.uploadFile(file).then(function(res) {
  console.log(res.data.link);
  console.error('https://imgur.com/delete/' + res.data.deletehash);
}, function(err) {
  console.error(err);
  process.exit(3);
});
