#!/usr/bin/env node

const fs = require('fs');
const imgur = require('imgur');

let file = process.argv[2];

if (!file) {
  console.error('Usage: imgur [IMAGE]');
  process.exit(1);
}

if (!fs.existsSync(file)) {
  console.error('File does not exist.');
  process.exit(2);
}

imgur.uploadFile(file).then(res => {
  console.log(res.data.link);
  console.error(`https://imgur.com/delete/${res.data.deletehash}`);
}, err => {
  console.error(err);
  process.exit(3);
});
