#!/bin/bash

set -eo pipefail
source "$(dirname "${BASH_SOURCE[0]}")"/.abash/abash.sh

UA=$(chromium-user-agent 2> /dev/null)
MODEL=${1:-$(grep -m1 '^model name' /proc/cpuinfo | sed -r 's/.*(i[[:digit:]][^\ ]*).*/\1/' )}

# Remove Core prefix
MODEL=${MODEL#i[3579]-}

SEARCH=$(curl -A "$UA" -sL "https://ark.intel.com/content/www/us/en/ark/search.html?_charset_=UTF-8&q=${MODEL}")

LINKS=(
  $(echo $SEARCH | pup '#FormRedirectUrl attr{value}')
  $(echo $SEARCH | pup '.result-title a attr{href}')
)

if [[ ${#LINKS[@]} == 0 ]]; then
  die 'No results found'
fi

LINK=${LINKS[0]}
URL="https://ark.intel.com${LINK}"

curl -A "$UA" -L --silent "$URL" |\
  pup '[data-key="CodeNameText"] a text{}' |
  xargs |
  sed 's/Products formerly //'
