#!/bin/bash

set -euo pipefail

source "$(dirname "${BASH_SOURCE[0]}")"/.abash/abash.sh

MODEL=${1:-$(grep -m1 '^model name' /proc/cpuinfo |
  sed -r 's/.*(i[[:digit:]][^\ ]*).*/\1/'
)}

SEARCH=$(curl -sL "https://ark.intel.com/search?_charset_=UTF-8&q=$MODEL")

LINKS=(
  $(echo $SEARCH | pup '#FormRedirectUrl attr{value}')
  $(echo $SEARCH | pup '.result-title a attr{href}')
)

if [[ ${#LINKS[@]} == 0 ]]; then
  die 'No results found'
fi

LINK=${LINKS[0]}
URL="https://ark.intel.com$LINK"

curl -L --silent "$URL" |\
  pup '[data-key="CodeNameText"] a text{}' |
  xargs |
  sed 's/Products formerly //'
