#!/bin/bash

set -eo pipefail
source $(dirname "${BASH_SOURCE[0]}")/.abash/abash.sh

arge help && usage '[-l, --lts, --longterm] [-s, --stable] [-m, --mainline]'

RELEASES=$(curl -s https://www.kernel.org/releases.json)

# default to stable, or default to longterm if an LTS kernel is running
MONIKER=stable
if uname -r | grep -qi '\b-lts\b'; then
  MONIKER=longterm
fi

arge lts && MONIKER=longterm
arge stable && MONIKER=stable
arge mainline && MONIKER=mainline

echo $RELEASES |
  jq -r --arg moniker "$MONIKER" \
  '[.releases[] | select(.moniker == $moniker)][0] | .version'
