#!/usr/bin/env node

(function() {
  'use strict';

  var request = require('request');
  var cheerio = require('cheerio');

  request('https://kernel.org', function(err, res, body) {
    if (err) { return console.error(err); }

    var $ = cheerio.load(body);
    var $latest = $('#latest_link > a');
    var latest = $latest.text().trim();

    console.log(latest);
  });
})();
