#!/bin/bash

CA_CONFIG_FILE="
  [req]
  prompt = no
  distinguished_name = dn

  [dn]
  O = localhost CA
  OU = localhost CA
  CN = localhost CA
"

CERT_CONFIG_FILE="
  [req]
  prompt = no
  req_extensions = san
  x509_extensions = san
  distinguished_name = dn

  [dn]
  O = localhost
  OU = localhost
  CN = localhost

  [san]
  subjectAltName = @alt_names

  [alt_names]
  DNS.1 = localhost
"

DNS=2
for ALT_NAME in "$@"; do
  [[ "$ALT_NAME" != *.* ]] && ALT_NAME+='.localhost'
  CERT_CONFIG_FILE+="  DNS.$DNS = ${ALT_NAME}"$'\n'
  let DNS+=1
done

openssl req -new -x509 \
  -days 3650 \
  -newkey rsa -nodes -keyout ca.key \
  -out ca.cer \
  -config <( echo -e "$CA_CONFIG_FILE" )

openssl req \
  -newkey rsa -keyout localhost.key -nodes \
  -out localhost.csr \
  -config <( echo -e "$CERT_CONFIG_FILE" )

openssl x509 -req \
  -days 3650 \
  -in localhost.csr \
  -CA ca.cer \
  -CAkey ca.key \
  -CAcreateserial \
  -out localhost.cer \
  -extensions san \
  -extfile <( echo -e "$CERT_CONFIG_FILE" )

cat localhost.cer > localhost-bundle.cer
cat ca.cer >> localhost-bundle.cer
