#!/bin/bash

source $(dirname "${BASH_SOURCE[0]}")/.abash/abash.sh

HIGHLIGHT_ARGS=()
arge ignore-case && HIGHLIGHT_ARGS+=('-i')

PATTERN=$(fnfarg)
exec /usr/bin/locate "$@" | highlight "$PATTERN" "${HIGHLIGHT_ARGS[@]}"
