#!/bin/bash

set -eo pipefail
source $(dirname "${BASH_SOURCE[0]}")/.abash/abash.sh

arge help && usage '[options]

  -f, --force    force kill and restart
'

pidof -s 1password &> /dev/null || exit

if arge force; then
  killall 1password &> /dev/null
  (1password --silent &> /dev/null &)
else
  (1password --silent --lock &> /dev/null &)
fi
