#!/bin/bash

source "$(dirname "${BASH_SOURCE[0]}")"/abash/abash.sh

ROOT=$(pwd)
DIRS=(*/)

for DIR in "${DIRS[@]}"; do
  PKG="${DIR%/}"

  if [ "$DIR" == "${DIRS[0]}" ]; then
    bannerline -f "$PKG"
  else
    bannerline "$PKG"
  fi

  cd "$ROOT/$PKG" && makepkg --noconfirm "$@"
done
