#!/bin/bash

source $(dirname "${BASH_SOURCE[0]}")/abash/abash.sh
[ -f "$1" ] || usage 'FILE'

KEYS=$(grep -o '^[0-9A-F]\{40\}' "$1")
[ -n "$KEYS" ] || die 'no keys found in file'

echo "$KEYS"
echo
confirm 'Import the above keys into makepkg keyring?'

for KEY in $KEYS; do
  echo Importing $KEY
  sudo makepkg-key --recv $KEY;
done
