#!/bin/bash

source "$(dirname "${BASH_SOURCE[0]}")"/abash/abash.sh

ROOT=$(pwd)
DIRS=(*/)

for DIR in "${DIRS[@]}"; do
  PKG="${DIR%/}"

  [ "$DIR" == "${DIRS[0]}" ] && bannerline -f "$PKG" || bannerline "$PKG"
  cd "$ROOT/$PKG" && makepkg --noconfirm "$@"
done
