#!/bin/bash

ACTION=$(cat /sys/block/md127/md/sync_action)
STATUS+=$ACTION

if [ "$ACTION" == "check" -o "$ACTION" == "recovery" ]; then
  PERCENT=$(grep % /proc/mdstat | cut -d'%' -f1 | awk '{ print $NF }')
  STATUS+=" (${PERCENT}%)"
fi

echo $STATUS
