#!/bin/bash

step() {
  printf "%.1f" "$(echo "scale=2; ${1}/1024" | bc)"
}

fmt() {
  awk '{
    if ($1 == int($1))
      printf "%d", $1
    else
      printf "%.1f", $1
  }'
}

if command -v vcgencmd &> /dev/null; then
  TOTAL_MEM_MB=$(vcgencmd get_config total_mem 2> /dev/null | awk -F= '/^total_mem=/ {print $2}')
fi

if [ -n "$TOTAL_MEM_MB" ]; then
  MEM_KB=$((TOTAL_MEM_MB * 1024))
else
  MEM_KB=$(awk '/^MemTotal:/ {print $2}' /proc/meminfo)
fi

MEM_MB=$(step "$MEM_KB")
MEM_GB=$(step "$MEM_MB")
MEM_TB=$(step "$MEM_GB")

if (( $(echo "$MEM_TB >= 1" | bc) )); then
  echo "$(printf "%s" "$MEM_TB" | fmt) TB"
elif (( $(echo "$MEM_GB >= 1" | bc) )); then
  echo "$(printf "%s" "$MEM_GB" | fmt) GB"
elif (( $(echo "$MEM_MB >= 1" | bc) )); then
  echo "$(printf "%s" "$MEM_MB" | fmt) MB"
else
  echo "$MEM_KB KB"
fi
