#!/bin/bash

source $(dirname "${BASH_SOURCE[0]}")/.abash/abash.sh

FILE=$(fnfarg)
[ -e "$FILE" ] || usage '[-x,--xdg] FILE'

if arge xdg; then
  exec xdg-mime query filetype "$FILE"
fi

exec file -b --mime-type "$FILE"
