#!/bin/bash

DT=/sys/firmware/devicetree/base
DMI=/sys/devices/virtual/dmi/id

if [ -d "$DT" ]; then
  cat "$DT"/model
  echo
elif [ -d "$DMI" ]; then
  NAMES=(
    "$(cat $DMI/board_name)"
    "$(cat $DMI/product_family)"
    "$(cat $DMI/product_name)"
  )

  MODEL=
  for NAME in "${NAMES[@]}"; do
    if [ "$NAME" != 'Default string' -a "${#NAME}" -gt "${#MODEL}" ]; then
      MODEL="$NAME"
    fi
  done

  echo $MODEL
fi
