#!/bin/bash

DT=/sys/firmware/devicetree/base
DMI=/sys/devices/virtual/dmi/id

if [ -d "$DT" ]; then
  tr -d '\0' < "$DT"/model
  echo
elif [ -d "$DMI" ]; then
  VENDOR=$(kat $DMI/board_vendor)

  NAMES=(
    "$(kat $DMI/board_name)"
    "$(kat $DMI/product_family)"
    "$(kat $DMI/product_name)"
  )

  MODEL=
  for NAME in "${NAMES[@]}"; do
    if [ "$NAME" != 'Default string' -a "${#NAME}" -gt "${#MODEL}" ]; then
      MODEL="$NAME"
    fi
  done

  echo $VENDOR $MODEL
fi
