#!/bin/bash

set -eo pipefail
source $(dirname "${BASH_SOURCE[0]}")/.abash/abash.sh

[ $# -eq 1 ] || usage 'MODULENAME'

MODULE=$1
PARAM_DIR=/sys/module/${MODULE}/parameters
[ -d ${PARAM_DIR} ] || die 'module has no parameters'

for PARAM in ${PARAM_DIR}/*; do
  [ -r ${PARAM} ] && VALUE=$(cat ${PARAM}) || VALUE=$(sudo cat ${PARAM})
  OUT="${OUT}$(basename ${PARAM})=${VALUE}\n"
done

echo -en ${OUT}
