#!/bin/bash
#
# Name: modparam
# Auth: Gavin Lloyd <gavinhungry@gmail.com>
# Desc: List loaded module parameters
#

source $(dirname "${BASH_SOURCE}")/abash/abash.sh
[ $# -ne 1 ] && usage "MODULENAME"

MODULE=$1
PARAM_DIR=/sys/module/${MODULE}/parameters
[ -d ${PARAM_DIR} ] || die "no parameters for '${MODULE}'"

for PARAM in ${PARAM_DIR}/*; do
  [ -r ${PARAM} ] && VALUE=$(cat ${PARAM}) || VALUE=$(sudo cat ${PARAM})
  OUT="${OUT}$(basename ${PARAM})=${VALUE}\n"
done

echo -en ${OUT}
