#!/bin/bash

for MODULE in $(awk '{ print $1 }' /proc/modules | sort); do
  # [ "$(modinfo -F intree $MODULE)" == "Y" ] || echo $MODULE
  [ "$(cat /sys/module/$MODULE/taint)" == "" ] || echo $MODULE
done
