#!/bin/bash

source $(dirname "${BASH_SOURCE[0]}")/.abash/abash.sh

MOTD_FILE=/etc/motd
MOTD_BANNER_FILE=/etc/motd-banner
MOTD_TAGLINE_FILE=/etc/motd-tagline
MOTD_WARNING_FILE=/etc/motd-warning

indent() {
  echo "$1" | sed 's/^/ /g'
}

print_motd_file() {
  local FILE_PATH=$1
  local FALLBACK_STR="$2"

  ! ispty && FILE_PATH=${FILE_PATH}.console

  if [ -f "$FILE_PATH" ]; then
    echo -e "\n$(indent "$(cat $FILE_PATH)")"
  elif [ -n "$FALLBACK_STR" ]; then
    echo -e "\n$(indent "$(echo $FALLBACK_STR)")"
  fi
}

print_motd_banner() {
  echo -en "\e[1;$(prompt-color $(pfarg color))m"
  print_motd_file $MOTD_BANNER_FILE "Welcome to $(hostname-pretty)"
  print_motd_file $MOTD_TAGLINE_FILE
  echo -en '\e[0m'
}

print_motd_body() {
  print_motd_file $MOTD_FILE
}

print_motd_warning() {
  print_motd_file $MOTD_WARNING_FILE
}

print_motd_banner
echo
echo " $(uname -sr)"
[ -n "$SSH_TTY" ] && echo " $(sshd -V 2>&1 | grep -im1 ssh)"
echo
echo " up $(uptimes)"
print_motd_body
arge warning && print_motd_warning
echo
