#!/bin/bash

source $(dirname "${BASH_SOURCE[0]}")/.abash/abash.sh
istty || exec termwin -t neofetch -c 'pause neofetch'

clear
echo

exec /usr/bin/neofetch \
  --ascii_bold off \
  --separator '\n' \
  --gap 4 \
  --refresh_rate on \
  --memory_unit gib \
  "$@"
