#!/bin/bash

source $(dirname "${BASH_SOURCE}")/abash/abash.sh
[ $# -eq 1 -o $# -eq 2 ] || usage "NETBIOS_NAME [NMB_SERVER]"

set -o pipefail

NETBIOS_NAME=${1%%.*}
NMB_SERVER=${2:-$NMB_SERVER}

[ -n "$NMB_SERVER" ] || die "NMB_SERVER not provided"

nmblookup -U $NMB_SERVER -R $NETBIOS_NAME | grep "${NETBIOS_NAME}<00>" | head -n1 | cut -d' ' -f1
