#!/bin/bash

source $(dirname "${BASH_SOURCE[0]}")/.abash/abash.sh

NODE=$(nwhich node)

NODE_FLAGS=(
  --experimental-fetch
)

NODE_REPL_FLAGS=(
  --experimental-repl-await
)

# ignore unsupported flags
if ! echo 'process.exit(0);' | $NODE ${NODE_FLAGS[@]} &> /dev/null; then
  NODE_FLAGS=()
fi

REPL_JS=$HOME/.node-repl.js

if [ ! -f "$REPL_JS" -o $# != 0 ]; then
  exec $NODE ${NODE_FLAGS[@]} "$@"
fi

exec $NODE ${NODE_FLAGS[@]} ${NODE_REPL_FLAGS[@]} "$REPL_JS"
