#!/bin/bash

source $(dirname "${BASH_SOURCE}")/abash/abash.sh

NPM=/usr/local/bin/npm
[ -x "$NPM" ] || exit 1

if arge g; then
  if [ $# -eq 2 -a "$2" == "update" ]; then
    for pkg in $(npm -g outdated --parseable --depth=0 | cut -d: -f4); do
      sudo $NPM -g install "$pkg"
    done
  else
    sudo $NPM "$@"
  fi
else
  $NPM "$@"
fi

