#!/bin/bash

source $(dirname "${BASH_SOURCE[0]}")/.abash/abash.sh

DEVICE_ID=$(lspci -m | grep -E "\b(NPU|Neural|AI Processor)\b" | awk '{ print $1; }')
[ -z "$DEVICE_ID" ] && exit 1

lspci -vm -s "$DEVICE_ID" |
  grep ^Vendor: -A1 | grep ^Device: |
  cut -d':' -f2 | cut -d'[' -f1 | trim
