#!/bin/bash

set -eo pipefail

MAX_CLOCK=$(nvidia-smi --query-gpu=clocks.max.graphics --format=csv,noheader,nounits)
LOAD_CLOCK=${NVIDIA_LOAD_CLOCK:-${MAX_CLOCK}}

PERCENT=$(nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader,nounits)
CLOCK=$(nvidia-smi --query-gpu=clocks.current.graphics --format=csv,noheader,nounits)

# scale with P-state
if [ $CLOCK -lt $LOAD_CLOCK ]; then
  PERCENT=$(echo "scale=0; $PERCENT * $CLOCK / $MAX_CLOCK" | bc)
fi

echo "${PERCENT}%"
