#!/bin/bash
#
# Name: open
# Auth: Gavin Lloyd
# Desc: semi-intelligent wrapper for exo-open
#

source $(dirname "${BASH_SOURCE}")/abash/abash.sh

if [ $# -eq 0 ]; then
  die "no file(s) specified"
fi

for FILE in "$@"; do

  if [ ! -e "$FILE" ]; then
    msg "'$FILE' does not exist"
    continue
  elif [ ! -r "$FILE" ]; then
    msg "no permission to read '$FILE'"
    continue
  fi

  exo-open "$FILE" &> /dev/null
done
