#!/bin/bash

source $(dirname "${BASH_SOURCE[0]}")/.abash/abash.sh

#
# workspace directory
#
# This is primarily a footgun-prevention mechanism, and not security
# enforcement. Allow workspaces either within `WORKSPACE_BASE_DIR`, even if it
# is just an explicitly-created symlink to an external directory.
#

WORKSPACE_BASE_DIR=${WORKSPACE_BASE_DIR:-$XDG_DEVEL_HOME}

[ -n "$WORKSPACE_BASE_DIR" ] || die 'WORKSPACE_BASE_DIR not set'
[ -d "$WORKSPACE_BASE_DIR" ] || die 'WORKSPACE_BASE_DIR does not exist'

WORKSPACE_DIR="$WORKSPACE_BASE_DIR"

if [[
  "$PWD" == "$WORKSPACE_BASE_DIR" ||
  "$PWD" == "$WORKSPACE_BASE_DIR"/*
]]; then
  WORKSPACE_DIR="$PWD"
else
  if ! arge help && ! arge version; then
    warn "Workspace should be within $WORKSPACE_BASE_DIR"
  fi
fi

#
# opencode
#
# Find standlone opencode x86 binary installed globally with pnpm. This avoids
# the postinstall script required by the platform-agnostic opencode-ai package.
#

OPENCODE_INSTALL_DIR=$(
  pnpm -g list --long --json |
  jq -r '.[0].dependencies["opencode-linux-x64"].path'
)

[ -d "$OPENCODE_INSTALL_DIR" ] || die 'opencode not installed'

#
# API keys
#
# Load API keys from pass, apply to environment variables and add `--setenv`
# args to pass to bwrap.
#

load_api_key() {
  local VAR_NAME=$1
  local API_KEY

  if API_KEY=$(pass "opencode/${VAR_NAME}" 2> /dev/null); then
    export "$VAR_NAME"="$API_KEY"
  fi
}

API_KEY_VAR_NAMES=(
  ANTHROPIC_API_KEY
  GOOGLE_GENERATIVE_AI_API_KEY
  OPENAI_API_KEY
)

if unlock-pass; then
  for VAR_NAME in "${API_KEY_VAR_NAMES[@]}"; do
    load_api_key "$VAR_NAME"
  done
fi

API_KEY_ARGS=()
for VAR_NAME in "${API_KEY_VAR_NAMES[@]}"; do
  if [ -n "${!VAR_NAME}" ]; then
    API_KEY_ARGS+=(--setenv "$VAR_NAME" "${!VAR_NAME}")
  fi
done

#
# editor
#
# Construct bwrap bind args for editor-specific user configurations
#

EDITOR_BIND_ARGS=()
if [ "$EDITOR" == emacs ]; then
  if [ -d '/usr/libexec/emacs' ]; then
    EDITOR_BIND_ARGS+=(--ro-bind /usr/libexec/emacs /usr/libexec/emacs)
  fi

  EDITOR_BIND_ARGS+=(--ro-bind /usr/share/emacs /usr/share/emacs)
  EDITOR_BIND_ARGS+=(--ro-bind "$HOME/.emacs" "$HOME/.emacs")
  EDITOR_BIND_ARGS+=(--ro-bind "$HOME/.emacs.d" "$HOME/.emacs.d")
fi

#
# external dir
#
# https://opencode.ai/docs/troubleshooting/#copypaste-not-working-on-linux
#
# `xclip` wrapper can be as simple as:
# cat > "$OPENCODE_SANDBOX_CLIPBOARD_FILE"
#

OPENCODE_SANDBOX_EXT_DIR=$(mktemp -d -p "$XDG_CACHE_HOME" opencode-ext-XXXX-$$)

OPENCODE_SANDBOX_CLIPBOARD_FILE="$OPENCODE_SANDBOX_EXT_DIR"/clipboard
touch "$OPENCODE_SANDBOX_CLIPBOARD_FILE"
surveil --path "$OPENCODE_SANDBOX_CLIPBOARD_FILE" clip 2> /dev/null &

ext_dir_cleanup() {
  # removing the directory containing the clipboard file will also kill surveil
  rm -fr "$OPENCODE_SANDBOX_EXT_DIR"
}

trap ext_dir_cleanup EXIT

#
# bwrap
#
# Execute bwrap and launch opencode.
#
# The opencode binary itself is executed within an interactive bash shell, with
# arguments to this script passed directly. This is a workaround for:
# https://github.com/anomalyco/opencode/issues/9860
#

/usr/bin/bwrap \
  --unshare-pid \
  --proc /proc \
  --dev /dev \
  --ro-bind /bin /bin \
  --ro-bind /usr/bin /usr/bin \
  --ro-bind /usr/share/terminfo /usr/share/terminfo \
  --ro-bind /lib /lib \
  --ro-bind /usr/lib /usr/lib \
  --ro-bind /lib64 /lib64 \
  --ro-bind /usr/lib64 /usr/lib64 \
  --ro-bind /etc/alternatives /etc/alternatives \
  --ro-bind /etc/resolv.conf /etc/resolv.conf \
  --ro-bind /etc/ssl /etc/ssl \
  --ro-bind "$OPENCODE_INSTALL_DIR" /opt/opencode \
  --dir "$HOME" \
  --tmpfs /tmp \
  --tmpfs "$XDG_CACHE_HOME" \
  --ro-bind "$XDG_LOCAL_HOME"/opt/opencode/bin "$XDG_LOCAL_HOME"/bin \
  --bind "$OPENCODE_SANDBOX_EXT_DIR" "$OPENCODE_SANDBOX_EXT_DIR" \
  --bind "$XDG_LOCAL_HOME"/opt/opencode/config "$XDG_CONFIG_HOME"/opencode \
  --bind "$XDG_LOCAL_HOME"/opt/opencode/data "$XDG_DATA_HOME"/opencode \
  --bind "$XDG_LOCAL_HOME"/opt/opencode/state "$XDG_STATE_HOME"/opencode \
  --bind "$WORKSPACE_DIR" "$WORKSPACE_DIR" \
  --chdir "$WORKSPACE_DIR" \
  --clearenv \
  --setenv HOME "$HOME" \
  --setenv PATH "$XDG_LOCAL_HOME"/bin:/usr/bin \
  --setenv PWD "$WORKSPACE_DIR" \
  --setenv TERM "$TERM" \
  --setenv EDITOR "drain-stdin $EDITOR" \
  --setenv XDG_CONFIG_HOME "$XDG_CONFIG_HOME" \
  --setenv XDG_LOCAL_HOME "$XDG_LOCAL_HOME" \
  --setenv XDG_DATA_HOME "$XDG_DATA_HOME" \
  --setenv XDG_STATE_HOME "$XDG_STATE_HOME" \
  --setenv XDG_CACHE_HOME "$XDG_CACHE_HOME" \
  --setenv OPENCODE_SANDBOX_EXT_DIR "$OPENCODE_SANDBOX_EXT_DIR" \
  --setenv OPENCODE_SANDBOX_CLIPBOARD_FILE "$OPENCODE_SANDBOX_CLIPBOARD_FILE" \
  --setenv OPENCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT 'true' \
  "${API_KEY_ARGS[@]}" \
  "${EDITOR_BIND_ARGS[@]}" \
/bin/bash -ic '
  /opt/opencode/bin/opencode "$@"
  drain-stdin
' /bin/bash "$@"
