#!/bin/bash

set -eo pipefail
source "$(dirname "${BASH_SOURCE[0]}")"/.abash/abash.sh

sudo -v || exit 1
sigint

update_pacman_packages() {
  bannerline -f 'Updating pacman packages'

  pacman -Syu --noconfirm
}

remove_unused_pacman_deps() {
  if pacman -Qdttq &> /dev/null; then
    bannerline 'Removing unrequired dependencies'
    pacman -Rsc $(pacman -Qdttq) --noconfirm
  fi
}

clean_pacman_cache() {
  bannerline 'Cleaning pacman cache'

  checksu paccache -rk1 | awk NF
  checksu paccache -ruk0 | awk NF
}

clean_pacman_cache_all() {
  bannerline 'Cleaning pacman cache'

  checksu paccache -rk0 | awk NF
}

update_apt_packages() {
  bannerline -f 'Updating apt packages'

  checksu apt update
  checksu apt full-upgrade
  checksu apt autoremove
}

update_dnf_packages() {
  bannerline -f 'Updating dnf packages'

  checksu dnf upgrade --refresh --assumeyes
  checksu dnf autoremove --assumeyes
}

__update_node() {
  local MACH=$(uname -m)
  local ARCH=

  [ "$MACH" = 'x86_64' ] && ARCH=x64
  [ "$MACH" = 'aarch64' ] && ARCH=arm64
  [ -z "$ARCH" ] && return

  local INDEX
  INDEX=$(curl -s https://nodejs.org/dist/index.json)

  local NODE_LATEST
  if [ "$1" = '--lts' ]; then
    NODE_LATEST=$(echo "$INDEX" | jq -r '[.[] | select(.lts != false)] | .[0].version')
  else
    NODE_LATEST=$(echo "$INDEX" | jq -r '.[0].version')
  fi

  local NODE_CURRENT=$(node --version 2> /dev/null)

  if [ "$NODE_CURRENT" = "$NODE_LATEST" ]; then
    echo "The latest version (${NODE_LATEST#v}) is already installed"
    return
  fi

  echo "Updating to $NODE_LATEST"
  checksu rm -fr /opt/node-v*-linux-${ARCH}

  wget -qO- "https://nodejs.org/dist/${NODE_LATEST}/node-${NODE_LATEST}-linux-${ARCH}.tar.xz" |\
    checksu tar --no-same-owner -xJC /opt/

  checksu ln -sf /opt/node-${NODE_LATEST}-linux-${ARCH}/bin/node /usr/local/bin/node
}

update_node() {
  bannerline 'Updating Node'

  __update_node
}

update_node_lts() {
  bannerline 'Updating Node (LTS)'

  __update_node --lts
}

update_bun() {
  bannerline 'Updating Bun'

  local MACH=$(uname -m)
  local ARCH=

  [ "$MACH" = 'x86_64' ] && ARCH=x64
  [ "$MACH" = 'aarch64' ] && ARCH=aarch64
  [ -z "$ARCH" ] && return

  local BUN_CURRENT=$(bun --version 2> /dev/null)
  local BUN_LATEST=$(curl -s https://api.github.com/repos/oven-sh/bun/releases/latest | jq -r '.tag_name' | sed -E 's/^bun-v?//')

  if [ "$BUN_CURRENT" = "$BUN_LATEST" ]; then
    echo "The latest version (${BUN_LATEST}) is already installed"
    return
  fi

  echo "Updating to $BUN_LATEST"
  checksu rm -fr /opt/bun-v*-linux-${ARCH}

  local TMP=$(mktemp)

  wget -qO "$TMP" "https://github.com/oven-sh/bun/releases/download/bun-v${BUN_LATEST}/bun-linux-${ARCH}.zip"
  checksu unzip -oqd /opt/ "$TMP"
  rm -f "$TMP"

  checksu ln -sf /opt/bun-linux-${ARCH}/bun /usr/local/bin/bun
}

update_pnpm() {
  bannerline 'Updating pnpm'

  pnpm self-update
}

update_npm_packages() {
  bannerline 'Updating npm packages'

  local PNPM_CONFIG_LOGLEVEL=error
  export PNPM_CONFIG_LOGLEVEL

  (pnpm -g outdated --json 2> /dev/null || true) |
  jq -r 'to_entries[] | .key + " " + .value.current + " " + .value.latest' |
  while read -r pkg current latest; do
    echo "$(color bold)$pkg$(color end) $current => $latest"
  done

  echo
  pnpm -g update --latest
  pnpm store prune
}

# ---

while IFS= read -r fn || [[ -n "$fn" ]]; do
  if (
    [[ "$fn" != _* ]] &&
    declare -F "$fn" > /dev/null &&
    grep -q "^${fn}()" "${BASH_SOURCE[0]}"
  ); then
    "$fn"
  fi
done < "$HOME/.os-update"
