#!/bin/bash

source $(dirname "${BASH_SOURCE}")/abash/abash.sh

[ $# -ge 2 ] || usage "OUTPUT PDF [PDF ...]"

GS=/usr/bin/gs

OUTPUT=$1; shift
INPUTS=$@

$GS -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite -sOutputFile=$OUTPUT $INPUTS
