#!/bin/bash

source $(dirname "${BASH_SOURCE}")/abash/abash.sh
[ $# -eq 0 ] && usage "PID"

int() {
  [ "$1" -eq "$1" ] &> /dev/null
}

for ARG in "$@"; do
  [[ "$ARG" == -* ]] && continue
  int $ARG && PID=$ARG || PID=$(pidof -s $ARG 2> /dev/null)

  SECS=$(ps -p $PID -o etimes= 2> /dev/null | sed s/^\\s*//g)
  if [ -n "$SECS" ]; then
    arge human && echo $(ddiff now $(dadd now +${SECS}s) -f '%dd, %Hh%Mm%Ss') || echo $SECS
    exit
  fi
done

exit 1
