#!/bin/bash

source $(dirname "${BASH_SOURCE}")/abash/abash.sh
[ $# -ge 1 ] || usage 'PID'

for ARG in $(nfargs); do
  PID=$(pidpid $ARG)

  SECS=$(ps -p $PID -o etimes= 2> /dev/null | sed s/^\\s*//g)
  if [ -n "$SECS" ]; then
    arge human && echo $(ddiff now $(dadd now +${SECS}s) -f '%dd, %Hh%Mm%Ss') || echo $SECS
    exit
  fi
done

exit 1
