#!/bin/bash

set -e

PID=$1
VAR=$2
[ -z "$PID" ] && exit 1

ENVIRON=/proc/$PID/environ
ENVIRON_OWNER=$(stat -c '%U' $ENVIRON 2> /dev/null)
ENV=$(sudo -u $ENVIRON_OWNER cat $ENVIRON 2> /dev/null | xargs -n1 -0)
[ -z "$ENV" ] && exit 2

if [ -n "$VAR" ]; then
  echo "$ENV" | awk -v V="$VAR" -v Z=3 -F= '$1==V {Z=0; print $2} END {exit Z}'
else
  echo "$ENV"
fi
