#!/bin/bash

# needed for SIPE
export NSS_SSL_CBC_RANDOM_IV=0

# always show the buddy list at launch
sed -ie "s/\(pref name='list_visible' type='bool' value\)='0'/\1='1'/" ${HOME}/.purple/prefs.xml
/usr/bin/pidgin -f
