#!/bin/bash

source $(dirname "${BASH_SOURCE[0]}")/abash/abash.sh
[ $# -eq 1 ] || usage 'PID'

PID=$(pidpid $1)
[ ! -e /proc/${PID}/status ] && exit 1

USER_ID=$(cat /proc/${PID}/status | grep ^Uid: |\
          sed -e 's/^.*:\t\([0-9]\+\).*$/\1/')
USER_NAME=$(awk -v val=${USER_ID} -F ":" '$3==val{print $1}' /etc/passwd)
[ -z ${USER_NAME} ] && exit 1

echo $USER_NAME
