#!/bin/bash

case "$PINENTRY_USER_DATA" in
  curses|gnome3|gtk|qt|qt5|tty)
    PINENTRY="/usr/bin/pinentry-${PINENTRY_USER_DATA}"
    if [ -x "$PINENTRY" ]; then
      exec "$PINENTRY" "$@"
    fi
  ;;
esac

exec /usr/bin/pinentry-curses "$@"
