#!/bin/bash

source $(dirname "${BASH_SOURCE[0]}")/.abash/abash.sh

MAX_LENGTH=$(arg max-length 0)
LABEL=$(arg label)

TITLE=$(playerctl -p $PLAYER_NAME metadata -f '{{artist}} • {{title}}' 2> /dev/null)
TITLE=${TITLE# - }

if [ "$TITLE" = 'YouTube Music' ]; then
  URL=$(playerctl -p $PLAYER_NAME metadata -f '{{xesam:url}}')
  TITLE=$(youtube-title "$URL")
fi

TITLE=${TITLE%% (*}
TITLE=${TITLE%% [*}

if [ -z "$TITLE" ]; then
  arge zwsp && echo -n "​" # zero-width space for Xfce genmon
  exit 1
fi

[ $MAX_LENGTH -gt 0 -a ${#TITLE} -gt $MAX_LENGTH ] && TITLE="${TITLE::$MAX_LENGTH} ..."

[ -n "$LABEL" ] && echo -n "$LABEL "
echo $TITLE
