#!/bin/bash

[ "$(id -u)" -eq 0 ] && exit 1
source $(dirname "${BASH_SOURCE[0]}")/.abash/abash.sh

PNPM=$(nwhich pnpm)
[ -x "$PNPM" ] || die 'pnpm not installed'

case "$1" in
  d|deps) shift; exec $PNPM install --frozen-lockfile ;;
  run) shift; exec $PNPM --silent run "$@" ;;
esac

exec $PNPM "$@"
