#!/bin/bash

source $(dirname "${BASH_SOURCE[0]}")/.abash/abash.sh

PNPM=$(nwhich pnpm)

case "$1" in
  d|deps) shift; exec $PNPM install --frozen-lockfile ;;
  run) shift; exec $PNPM --silent run "$@" ;;
esac

exec $PNPM "$@"
