#!/bin/bash

source $(dirname "${BASH_SOURCE[0]}")/.abash/abash.sh

format_color() {
  if arge invert; then
    ispty && echo "2;7;3$1" || echo "4$1;97"
  else
    ispty && echo "2;3$1" || echo "$1;97"
  fi
}

# root
if [ $(id -u) -eq 0 ]; then
  echo $(format_color 1)
  exit
fi

PROMPT_COLOR_FILE=$(console_file_path /etc/prompt-color)

# local user
if [ -z "$SSH_TTY" -o ! -f $PROMPT_COLOR_FILE ]; then
  ispty && echo '1;97' || echo '37'
  exit
fi

cat $PROMPT_COLOR_FILE
