#!/bin/bash

source $(dirname "${BASH_SOURCE}")/abash/abash.sh

PROFILE_NAME=$(fnfarg); shift
PROFILE_DIR=$(readlink -f ${HOME}/.vm/${PROFILE_NAME:-default})
PROFILE=${PROFILE_DIR}/qemu.conf

[ -r "${PROFILE}" ] || die 'profile not found'
source "${PROFILE}"

TITLE=${TITLE:-$PROFILE_NAME}
WM_ICON="${PROFILE_DIR}/icon.png"
[ -r "${WM_ICON}" ] || WM_ICON="${HOME}/.icons/qemu.png"
(sleep 1; xseticon -name "QEMU (${TITLE})" "$WM_ICON") &

exec qemu-system-x86_64 \
  -name "${TITLE}" \
  -smp ${SMP:-1},cores=${CORES:-1} \
  -m ${MEMORY:-1G} \
  ${ARGS} \
  "$@"
