#!/bin/bash

source $(dirname "${BASH_SOURCE[0]}")/.abash/abash.sh

PROFILE_DIR=${HOME}/.rdp
PROFILE_NAME=$(fnfarg)
PROFILE=$(readlink -f ${PROFILE_DIR}/${PROFILE_NAME:-default})

[ -f "$PROFILE" ] || die 'profile not found'
source "$PROFILE"

RDP_WIN_TITLE="${RDP_TITLE:-$RDP_SERVER}  —  Remote Desktop"

if [ -z "$RDP_PASSWORD" ]; then
  RDP_PASSWORD=$(zenity --password --title="$RDP_WIN_TITLE")
fi

[ -z "$RDP_PASSWORD" ] && exit 1

[ -n "$RDP_PROXY" ] && RDP_ARGS+=" /proxy:$RDP_PROXY"
[ -n "$RDP_PORT" ] && RDP_ARGS+=" /port:$RDP_PORT"
arge fullscreen && RDP_ARGS+=" /f"

RDP_GEOMETRY=${RDP_GEOMETRY:-1920x1080}
RDP_WIDTH=${RDP_GEOMETRY%x*}
RDP_HEIGHT=${RDP_GEOMETRY#*x}

exec xfreerdp \
  /title:"$RDP_WIN_TITLE" \
  /gfx:AVC444 \
  /bpp:24 \
  /audio-mode:1 \
  /dynamic-resolution \
  +toggle-fullscreen \
  +window-drag \
  +clipboard \
  /w:"${RDP_WIDTH}" \
  /h:"${RDP_HEIGHT}" \
  /v:"${RDP_SERVER}" \
  /d:"${RDP_DOMAIN}" \
  /u:"${RDP_USER}" \
  /p:"${RDP_PASSWORD}" \
  ${RDP_ARGS}
