#!/bin/bash

source $(dirname "${BASH_SOURCE[0]}")/abash/abash.sh

unset RDP_SERVER
unset RDP_NMB
unset RDP_DOMAIN
unset RDP_USER
unset RDP_PASSWORD
unset RDP_WIDTH
unset RDP_HEIGHT
unset RDP_ARGS

PROFILE_DIR=${HOME}/.rdp
PROFILE_NAME=$(fnfarg)
PROFILE=$(readlink -f ${PROFILE_DIR}/${PROFILE_NAME:-default})

[ -f ${PROFILE} ] || die 'profile not found'

source "$PROFILE"

WINDOW_TITLE="${RDP_TITLE:-$RDP_SERVER} - Remote Desktop"

if [ "$RDP_NMB" == "1" ]; then
  RDP_SERVER=$(nmbip "$RDP_SERVER")
fi

if arge fullscreen; then
  RDP_ARGS+=" /f"
fi

exec xfreerdp \
  /bpp:24 \
  /network:lan \
  /audio-mode:1 \
  ${RDP_ARGS} \
  /title:"$WINDOW_TITLE" \
  /v:"${RDP_SERVER}" \
  /d:"${RDP_DOMAIN}" \
  /u:"${RDP_USER}" \
  /p:"${RDP_PASSWORD}" \
  /w:"${RDP_WIDTH}" \
  /h:"${RDP_HEIGHT}"
