#!/bin/bash

source $(dirname "${BASH_SOURCE[0]}")/abash/abash.sh

PROFILE_NAME=$(fnfarg)
PROFILE_NAME=${PROFILE_NAME%.rdp}
PROFILE_DIR=${HOME}/.rdp
PROFILE=$(readlink -f ${PROFILE_DIR}/${PROFILE_NAME:-default}.rdp)

[ -f ${PROFILE} ] || die 'profile not found'

RDP_TITLE=$(grep "^title:s:" ${PROFILE} | cut -d':' -f3)
RDP_HOSTNAME=$(grep "^full address:s:" ${PROFILE} | cut -d':' -f3)
RDP_NETBIOS=$(grep "^use netbios:i:" ${PROFILE} | cut -d':' -f3-)
RDP_OPTIONS=$(grep "^xfreerdp:s:" ${PROFILE} | cut -d':' -f3-)
PROXY_COMMAND=$(grep "^proxycommand:s:" ${PROFILE} | cut -d':' -f3-)

# FIXME: need to accept certificate
if [ ${RDP_NETBIOS:-0} -eq 1 ]; then
  NMB_PROFILE=${PROFILE%.*}.nmb.rdp
  rm -f ${NMB_PROFILE}
  sed "s/^\(full\ address:s:\).*/\1$(nmbip ${RDP_HOSTNAME})/" ${PROFILE} > ${NMB_PROFILE}
  sed "s/^\(use\ netbios:i:\).*/\10/" -i ${NMB_PROFILE}
  PROFILE=${NMB_PROFILE}
fi

shift

if arge fullscreen; then
  RDP_OPTIONS+=' /f /toggle-fullscreen'
fi

if [ -n "$PROXY_COMMAND" ]; then
  $PROXY_COMMAND &
  PROXY_COMMAND_PID=$!
  sleep 2
fi

xfreerdp ${PROFILE} /title:"${RDP_TITLE:-$RDP_HOSTNAME} - Remote Desktop" ${RDP_OPTIONS} $(arg args)
[ -n "$PROXY_COMMAND_PID" ] && kill $PROXY_COMMAND_PID
