#!/bin/bash

set -eo pipefail
source $(dirname "${BASH_SOURCE[0]}")/.abash/abash.sh

[ $# -ge 2 ] || exit 1

THEN=$1
if [[ $1 != *:* ]]; then
  [[ $1 = *s ]] && THEN+="econds"
  [[ $1 = *m ]] && THEN+="inutes"
  [[ $1 = *h ]] && THEN+="ours"
  [[ $1 = *d ]] && THEN+="ays"
fi

shift

THEN_S=$(faketime $THEN date +%s)
DUR_S=$(( $THEN_S - $(date +%s) ))
[ $DUR_S -ge 0 ] || exit 1

(xsleep $DUR_S;
  NOW=$(date '+%I:%M %p')
  while pgrep xsecurelock > /dev/null; do xsleep 1; done;
  notify-send -t 0 "Reminder ($NOW)" "$*") &

echo "Reminder due at $(faketime $THEN date)"
