#!/usr/bin/env node

const { parseArgs } = require('node:util');
const cheerio = require('cheerio');
const open = require('open');

const OS_NAMES = ['linux', 'windows', 'mac'];

const { values } = parseArgs({
  options: {
    os:     { short: 'o', type: 'string',  default: OS_NAMES[0] },
    arm:    { short: 'a', type: 'boolean', default: false },
    studio: { short: 's', type: 'boolean', default: false },
    beta:   { short: 'b', type: 'boolean', default: false },
  },
  strict: false,
});

const OS_NAME   = values.os;
const IS_ARM    = values.arm;
const IS_STUDIO = values.studio;
const IS_BETA   = values.beta;

if (!OS_NAMES.includes(OS_NAME)) {
  console.log('Unknown OS');
  process.exit(1);
}

fetch('https://www.blackmagicdesign.com/support/partial/downloads')
  .then(res => res.text())
  .then(cheerio.load)
  .then($dom => {
    let selector = 'article[software-download][name^="DaVinci Resolve"]';
    selector += IS_STUDIO ? '[name*="Studio"]' : ':not([name*="Studio"])';
    selector += IS_BETA ? '[name*="Beta"]' : ':not([name*="Beta"])';

    const $el = $dom(selector).first();
    const version = $el.attr('name');

    selector = `a.download.${OS_NAME}`;
    if (IS_ARM) {
      selector += '[href$=" ARM"]';
    }

    const href = $el.find(selector).attr('href');
    return { version, href };
  })
  .then(({ version, href }) => {
    if (!href) {
      console.error(`No ${IS_BETA ? 'beta' : 'stable'} version found`);
      process.exit(1);
    }

    let osString = href.split('/').at(-1);
    if (!osString) {
      osString = OS_NAME;
    }

    console.log(`${version} for ${osString}`);
    return `https://www.blackmagicdesign.com${href}`;
  })
  .then(open.default);
