#!/bin/bash

exec rofi -kb-cancel 'Escape,Pause' -disable-history \
  -modi combi -show combi -combi-modi drun,run \
  -drun-display-format "{name}" -drun-match-fields name \
  -sort -sorting-method levenshtein \
  -normalize-match "$@"
