#!/bin/bash

set -eo pipefail
source $(dirname "${BASH_SOURCE[0]}")/.abash/abash.sh

arge help && usage '[options]

  -d, --dry-run     do not restart services
  -h, --help        this message
'

SERVICES=()

for SERVICE in $(systemctl list-units --type=service --state=running | awk '{print $1}' | grep \.service$); do
  systemctl status $SERVICE 2>&1 | grep -q "$SERVICE changed on disk" && SERVICES+=($SERVICE)
done

[ ${#SERVICES[@]} -gt 0 ] || exit 0

arge dry-run || systemctl daemon-reload

for SERVICE in "${SERVICES[@]}"; do
  echo $SERVICE
  arge dry-run || systemctl restart $SERVICE
done
