#!/bin/bash

set -eo pipefail

CMD=${1:-'--fullscreen'}
FILENAME=${XDG_DESKTOP_DIR}/$(date +"screenshot-%Y%m%d-%H%M%S-%3N.png")

case "$CMD" in
  -f|--fullscreen|-r|--region|-w|--window)
    xfce4-screenshooter "$CMD" --save "$FILENAME"
  ;;

  -b|--borderless-window)
    # xfce4-screenshooter doesn't seem to allow capturing borderless windows
    scrot --focused "$FILENAME"
  ;;
esac

clip "$FILENAME"
