#!/bin/bash

set -euo pipefail

CMD=${1:-'--fullscreen'}
FILENAME=${HOME}/$(date +"screenshot-%Y%m%d-%H%M%S-%3N.png")

case "$CMD" in
  -f|--fullscreen|-r|--region)
    # scrot doesn't have very good region selection
    xfce4-screenshooter "$CMD" --save "$FILENAME"
  ;;

  -w|--window)
    # xfce4-screenshooter doesn't seem to allow capturing borderless windows
    scrot --focused "$FILENAME"
  ;;
esac

clip "$FILENAME"
