#!/bin/bash

set -eo pipefail
source $(dirname "${BASH_SOURCE[0]}")/.abash/abash.sh

[ $# -eq 2 ] || usage '[NAME] [KEYSIZE]'

OPENSSL=/usr/bin/openssl

NAME=$1
KEYSIZE=$2
TMP=$(tmpdir $NAME)

[ -f ${NAME}.key ] && die "${NAME}.key already exists"
[ -f ${NAME}.crt ] && die "${NAME}.crt already exists"

${OPENSSL} genrsa -des3 -out ${TMP}/${NAME}.key ${KEYSIZE}
${OPENSSL} req -new -key ${TMP}/${NAME}.key -out ${TMP}/${NAME}.csr
cp ${TMP}/${NAME}.key ${TMP}/${NAME}.key.orig
${OPENSSL} rsa -in ${TMP}/${NAME}.key.orig -out ${NAME}.key
${OPENSSL} x509 -req -days 3650 -in ${TMP}/${NAME}.csr -signkey ${NAME}.key -out ${NAME}.crt

tmpdirclean
