#!/bin/bash

source $(dirname "${BASH_SOURCE}")/abash/abash.sh
[ $# -le 2 ] || usage "[NAME] [KEYSIZE]"

OPENSSL=/usr/bin/openssl
TMPDIR=/tmp

NAME=${1:-server}
KEYSIZE=${2:-1024}

[ -f ${NAME}.key ] && die "${NAME}.key already exists"
[ -f ${NAME}.crt ] && die "${NAME}.crt already exists"

${OPENSSL} genrsa -des3 -out ${TMPDIR}/${NAME}.key ${KEYSIZE}
${OPENSSL} req -new -key ${TMPDIR}/${NAME}.key -out ${TMPDIR}/${NAME}.csr
cp ${TMPDIR}/${NAME}.key ${TMPDIR}/${NAME}.key.orig
${OPENSSL} rsa -in ${TMPDIR}/${NAME}.key.orig -out ${NAME}.key
${OPENSSL} x509 -req -days 3650 -in ${TMPDIR}/${NAME}.csr -signkey ${NAME}.key -out ${NAME}.crt

rm ${TMPDIR}/${NAME}.key{,.orig} ${TMPDIR}/${NAME}.csr
