#!/bin/bash

set -euo pipefail

source $(dirname "${BASH_SOURCE[0]}")/.abash/abash.sh
arge help && usage '[options]

  -v, --visual      include visual ASCII art representation
  -t, --type        limit output to key type
  -h, --help        this message
'

PUBKEYS=(/etc/ssh/ssh_host_$(arg type '*')_key.pub)

for N in "${!PUBKEYS[@]}"; do
  FINGERPRINT=$(ssh-keygen -lvf "${PUBKEYS[$N]}")
  echo "$FINGERPRINT" | head -n1 | awk '{print $2" "$NF;}'
  if arge visual; then
    echo "$FINGERPRINT" | tail -n+2
    [ $N -lt $((${#PUBKEYS[@]} - 1)) ] && echo
  fi
done
