#!/bin/bash

if ! grep -q "^${1}$" <(ssh-aliases); then
  echo "Host alias not found" >&2
  exit 1
fi

MNT_DIR=~/.cache/mount/$1

mkdir -pm 700 "$MNT_DIR"
sshfs -o follow_symlinks -o workaround=rename $1:$2 "$MNT_DIR"
