#!/bin/bash

if [ ! $(pidof X) ]; then
  XAUTH=${HOME}/.Xauthority
  rm -f ${XAUTH}
  touch ${XAUTH}
fi

rm -fr ${HOME}/.cache/sessions

cd ${HOME}
/usr/bin/startx "$@" 2>&1 | grep -Ev '^Kernel command line|fbcon|Initializing built-in|Loading extension' >&2
