#!/bin/bash

source $(dirname "${BASH_SOURCE[0]}")/.abash/abash.sh
[ $# -ge 1 ] || usage 'FILES "COMMAND"'

FILES=${@:1:$(($#-1))}
COMMAND=${@: -1}

for FILE in $FILES; do
  [ -r $FILE ] || die "cannot read surveillance target: $FILE"
done

eval $COMMAND

while true; do
  inotifywait -qqe modify,attrib $FILES && sync $FILES && eval $COMMAND || sleep 1
done
