#!/bin/bash

source $(dirname "${BASH_SOURCE}")/abash/abash.sh

case $(fnfarg) in
  list-*|is-*|show-*|show|status|'')
    /usr/bin/systemctl "$@" ;;
  *)
    /usr/bin/sudo -E /usr/bin/systemctl "$@" ;;
esac
