#!/bin/bash

# find first command argument
for ARG in "$@"; do
  [[ $ARG != -* ]] && CARG=$ARG && break
done

case $CARG in
  list-*|is-*|show-*|show|status|'')
    /usr/bin/systemctl "$@" ;;
  *)
    /usr/bin/sudo /usr/bin/systemctl "$@" ;;
esac
