#!/bin/bash

clean() {
  local CLEAN=$(echo -n "$1" | tr -cd '[:alnum:] [:space:] ._-' | tr -s '[:space:]' '-')
  echo "${CLEAN#.}"
}

[ -d "$1" ] && exec tar -I 'zstd -T0' -cvf "$(clean "$1").tar.zst" "$1" # create
[ -f "$1" ] && exec tar xvf "$1" # extract
