#!/bin/bash

source $(dirname "${BASH_SOURCE[0]}")/.abash/abash.sh

declare -A STATUS_COLOR_MAP

STATUS_COLOR_MAP[available]='#003000'
STATUS_COLOR_MAP[busy]='#000033'
STATUS_COLOR_MAP[do_not_disturb]='#000033'
STATUS_COLOR_MAP[be_right_back]='#3A1000'
STATUS_COLOR_MAP[away]='#3A1000'

STATUS_COLOR_MAP[in_a_call]='#440000'

LAST_STATUS=

update() {
  STATUS=$(teams-status)
  [ "$STATUS" == "$LAST_STATUS" ] && return

  LAST_STATUS=$STATUS
  echo $STATUS

  if [ -z "$STATUS" -o "$STATUS" == 'offline' ]; then
    busylight off
    return
  fi

  STATUS_COLOR=${STATUS_COLOR_MAP[$STATUS]}
  if [ -z "$STATUS_COLOR" ]; then
    echo "Unknown status: $STATUS"
    return
  fi

  busylight on "$STATUS_COLOR"
}

while true; do
  update
  xsleep 2
done
