#!/bin/bash

# root
if [ "$(id -u)" -eq 0 ]; then
  exec printf '\033]11;#140000\033\\'
fi

# SSH with per-host TERM_BG_COLOR
if [ -n "$SSH_TTY" ] && [ -n "$TERM_BG_COLOR" ]; then
  exec printf '\033]11;#%s\033\\' "$TERM_BG_COLOR"
fi

# reset
exec printf '\033]111\033\\'
