#!/bin/bash

source $(dirname "${BASH_SOURCE[0]}")/.abash/abash.sh

format_color() {
  ispty && echo "2;3$1" || echo "9$1"
}

# root
if [ "$(id -u)" -eq 0 ]; then
  echo $(format_color 1)
  exit
fi

# local user
if (! arge color && [ -z "$SSH_TTY" ]) || [ -z "$TERM_FG_COLOR" ]; then
  ispty && echo '97' || echo '37'
  exit
fi

format_color $TERM_FG_COLOR
