#!/bin/bash

source $(dirname "${BASH_SOURCE[0]}")/.abash/abash.sh

format_color() {
  ispty && echo "2;3$1" || echo "9$1"
}

if arge motd; then
  format_color ${MOTD_FG_COLOR:-${TERM_FG_COLOR}}
  exit
fi

# root
if [ "$(id -u)" -eq 0 ]; then
  echo $(format_color 1)
  exit
fi

# local user
if [ -z "$SSH_TTY" ] || [ -z "$TERM_FG_COLOR" ]; then
  ispty && echo '97' || echo '37'
  exit
fi

format_color $TERM_FG_COLOR
