#!/bin/bash

set -eo pipefail
source $(dirname "${BASH_SOURCE[0]}")/.abash/abash.sh

([ $# -lt 1 ] || arge help) && usage '[options] $PROGRAM'

EXE=$1
which $EXE > /dev/null

KILL_EXE=${2:-$EXE}

if pidofuser $USER $KILL_EXE; then
  killall -u $USER $KILL_EXE
  exit
fi

exec one $EXE &
