#!/bin/bash

set -eo pipefail
source $(dirname "${BASH_SOURCE[0]}")/.abash/abash.sh

TRUNK_CONF=${TRUNK_CONF:-/etc/trunk}

TRUNK_MAPPER=${TRUNK_MAPPER:-trunk}
TRUNK_MAPPER_DEVICE=${TRUNK_MAPPER_DEVICE:-/dev/mapper/$TRUNK_MAPPER}
TRUNK_MOUNTPOINT=${TRUNK_MOUNTPOINT:-/trunk}
TRUNK_STATEFILE=${TRUNK_STATEFILE:-/run/trunk.state}

TRUNK_LUKS_HEADER=${TRUNK_LUKS_HEADER:-/etc/luks/trunk.header}
TRUNK_LUKS_KEYFILE=${TRUNK_LUKS_KEYFILE:-/etc/luks/trunk.key}

declare -A TRUNK
TRUNK_ORDER=()

while IFS=':' read -r KEY VALUE; do
  TRUNK["$KEY"]="$VALUE"
  TRUNK_ORDER+=("$KEY")
done < "$TRUNK_CONF"

parse_trunk() {
  local PAIR KEY VALUE OUTPUT
  IFS=',' read -r -a PAIRS <<< "$1"

  for PAIR in "${PAIRS[@]}"; do
    KEY=${PAIR%%=*}
    VALUE=${PAIR#*=}

    OUTPUT+="local TRUNK_${KEY^^}="$VALUE"\n"
  done

  echo -e "$OUTPUT"
}

is_mountpoint() {
  mountpoint "$1" &> /dev/null
}

get_trunk_state() {
  cat "$TRUNK_STATEFILE" 2> /dev/null
}

get_disk_device_by_uuid() {
  echo /dev/disk/by-uuid/"$TRUNK_UUID"
}

get_auto_trunk_id() {
  for TRUNK_ID in "${TRUNK_ORDER[@]}"; do
    $(parse_trunk ${TRUNK[$TRUNK_ID]})

    case "$TRUNK_TYPE" in
      disk)
        if [ -b "$(get_disk_device_by_uuid "$TRUNK_UUID")" ]; then
          echo "$TRUNK_ID"
          return
        fi
      ;;

      ragnar)
        echo "$TRUNK_ID"
        return
      ;;
    esac
  done
}

trunk_ragnar() {
  local TRUNK_ID=$1
  $(parse_trunk ${TRUNK[$TRUNK_ID]})

  if [ "$TRUNK_TYPE" == 'ragnar' ]; then
    RAGNAR_SSH_SERVER="$TRUNK_HOST" \
    RAGNAR_NBD_EXPORT="$TRUNK_EXPORT" \
    RAGNAR_NBD_LOCAL_PORT="$TRUNK_PORT" \
    /usr/bin/ragnar "$2"
  fi
}

open() {
  local TRUNK_ID=$1 DEVICE

  if [ -z "$TRUNK_ID" -o "$TRUNK_ID" == 'auto' ]; then
    TRUNK_ID=$(get_auto_trunk_id)
  fi

  local _TRUNK_STATE=$(get_trunk_state)
  [ -z "$_TRUNK_STATE" ] || die "Trunk '$_TRUNK_STATE' already active"
  [[ -v TRUNK[$TRUNK_ID] ]] || die "Trunk '$TRUNK_ID' not defined"
  [ -b "$TRUNK_MAPPER_DEVICE" ] && die 'Trunk device already open'

  inform "Opening trunk '$TRUNK_ID'"
  $(parse_trunk ${TRUNK[$TRUNK_ID]})

  case "$TRUNK_TYPE" in
    disk) DEVICE=$(get_disk_device_by_uuid "$TRUNK_UUID") ;;
    ragnar) DEVICE=$(trunk_ragnar "$TRUNK_ID" attach) ;;
    "") die 'Trunk not defined' ;;
    *) die "Unknown trunk type '$TRUNK_TYPE'" ;;
  esac

  [ -b "$DEVICE" ] || die 'Trunk device not attached'

  inform "Opening '$DEVICE'"
  checksu cryptsetup luksOpen "$DEVICE" "$TRUNK_MAPPER" \
    --allow-discards \
    --header "$TRUNK_LUKS_HEADER" \
    --key-file "$TRUNK_LUKS_KEYFILE"

  inform "Mounting '$TRUNK_MOUNTPOINT'"
  checksu mount -o compress=zstd,subvolid=5 \
    "$TRUNK_MAPPER_DEVICE" "$TRUNK_MOUNTPOINT"

  echo "$TRUNK_ID" | checksu tee "$TRUNK_STATEFILE" > /dev/null
}

close() {
  local TRUNK_ID=$(get_trunk_state)
  [ -z "$TRUNK_ID" ] && die 'No active trunk'

  inform "Closing trunk '$TRUNK_ID'"

  inform "Unmounting '$TRUNK_MOUNTPOINT'"
  checksu umount "$TRUNK_MOUNTPOINT"

  inform "Closing '$TRUNK_MAPPER_DEVICE'"
  checksu cryptsetup luksClose "$TRUNK_MAPPER"

  trunk_ragnar "$TRUNK_ID" detach
  checksu rm "$TRUNK_STATEFILE"
}

list() {
  for TRUNK_ID in "${TRUNK_ORDER[@]}"; do
    echo "$TRUNK_ID"
  done
}

case "$1" in
  open) open "$2" ;;
  close) close ;;
  list) list ;;
  status) get_trunk_state ;;
esac
