#!/bin/bash

PASS_GPG_ID_FILE="${PASSWORD_STORE_DIR:-${HOME}/.password-store}"/.gpg-id
[ -r "$PASS_GPG_ID_FILE" ] || exit 1

PASS_GPG_ID=$(cat "$PASS_GPG_ID_FILE")
[ -n "$PASS_GPG_ID" ] || exit 2

exec unlock-gpg "$PASS_GPG_ID"
