#!/usr/bin/env node

(function() {
  'use strict';

  var fs = require('fs');
  var path = require('path');

  var chromePath = path.join(process.env.HOME, '.config/google-chrome');
  var profilePath = path.join(chromePath, 'Default');
  var prefsPath = path.join(profilePath, 'Preferences');
  var lockPath = path.join(chromePath, 'SingletonLock');

  try {
    fs.lstatSync(lockPath);

    console.error('Chrome is running!');
    process.exit(1);
  } catch(err) {}

  try {
    var prefsBuffer = fs.readFileSync(prefsPath);
    var prefs = JSON.parse(prefsBuffer);
  } catch(err) {
    console.error('Could not read or parse Preferences file!');
    process.exit(1);
  }

  prefs.pinned_tabs = [];
  fs.writeFileSync(prefsPath, JSON.stringify(prefs));
})();
