#!/bin/bash

source $(dirname "${BASH_SOURCE}")/abash/abash.sh
[ -r ${HOME}/.vmx ] && source ${HOME}/.vmx

next_display() {
  X_DISP_DIR=/tmp/.X11-unix
  DISP_NO=0

  while [ -e ${X_DISP_DIR}/X${DISP_NO} ]; do
    let DISP_NO=$DISP_NO+1
  done

  echo :${DISP_NO}
}

VMX=$1
[ -e "${VMX}" ] || usage [VMX]

VMXNAME=$(grep ^displayName $VMX | sed 's/.*=\s*"\(.*\)"/\1/g')

DISP=$(next_display)
TITLE="VMware - ${VMXNAME:-(unnamed)} (${DISP})"

Xephyr -no-host-grab -title "${TITLE}" -resizeable -screen ${XEPHYR_RES:-1280x800} ${DISP} &
XEPHYR_PID=$!

sleep 0.5
xseticon -name "${TITLE}" /usr/share/icons/hicolor/16x16/apps/vmware-workstation.png

DISPLAY=${DISP} xfwm4 &
DISPLAY=${DISP} vmplayer "${VMX}" --fullscreen
kill ${XEPHYR_PID}
