#!/bin/bash

playback() {
  CMD="$@"

  if [ "$CMD" == 'mute' -o "$CMD" == 'unmute' -o "$CMD" == 'toggle' ]; then
    if [ "$CMD" == 'toggle' ]; then
      CMD='unmute'
      amixer -M -D pulse get Master | grep -q '\[on\]' && CMD='mute'
    fi
  fi

  amixer -Mq -D pulse set Master playback "$CMD"
}

case $1 in
  '') exit ;;
  up) playback 2%+ ;;
  down) playback 2%- ;;
  *) playback "$@" ;;
esac
