#!/bin/bash

source $(dirname "${BASH_SOURCE[0]}")/.abash/abash.sh

VULNS_DIR=/sys/devices/system/cpu/vulnerabilities
MAX_LENGTH=0

[ -d $VULNS_DIR ] ||  exit 1

for VULN in ${VULNS_DIR}/*; do
  VULN_NAME=$(basename $VULN)

  if [ ${#VULN_NAME} -gt $MAX_LENGTH ]; then
    MAX_LENGTH=${#VULN_NAME}
  fi
done

for VULN in ${VULNS_DIR}/*; do
  VAL=$(cat $VULN)
  COLOR=yellow
  [ "$VAL" == "Not affected" ] && COLOR=green
  [ "$VAL" == "Vulnerable" ] && COLOR=red
  printf " $(color bold $COLOR)%${MAX_LENGTH}s$(color end): %s\n" \
    "$(basename $VULN)" \
    "$VAL"
done
