#!/bin/bash

set -eo pipefail

PATH=$PATH:$(dirname ${BASH_SOURCE[0]})

wsl-interop > /dev/null || exit 1
eval $(wsl-interop)

[ -z "$1" ] && exit 1

# echo with \n only
echo $(cmd.exe /C "echo | set /p=%${1}%& exit /b 0" 2> /dev/null)
