#!/bin/bash

#
# eval "$(wsl-interop)"
#

set -eo pipefail
source $(dirname "${BASH_SOURCE[0]}")/.abash/abash.sh

[ ! -d /run/WSL ] && die 'WSL is not active'
[ -n "$WSL_INTEROP" ] && exit

# oldest interop (init?) does not work, use second oldest
WSL_INTEROP=$(
  find /run/WSL -type s -printf '%T+ %p\n' \
  | sort | head -2 | tail -1 | cut -d' ' -f2-
)

echo "export WSL_INTEROP=$WSL_INTEROP"
