#!/bin/bash

set -eo pipefail

PATH=$PATH:$(dirname ${BASH_SOURCE[0]})
wsl-interop > /dev/null; eval $(wsl-interop)

exec /mnt/c/Windows/System32/rundll32.exe \
  'C:\Windows\System32\user32.dll',LockWorkStation
