#!/bin/bash

set -eo pipefail

PATH=$PATH:$(dirname ${BASH_SOURCE[0]})

wsl-interop > /dev/null || exit 1
eval $(wsl-interop)

exec cmd.exe \
  /C "query session $(wsl-env-var USERNAME)& exit /b 0" 2>&1 \
  | grep 'rdp-tcp#0' > /dev/null
