#!/bin/bash

JSON=$(curl -s https://wttr.in/$WX_LOCATION?format=j1)

WX_DESC=$(echo $JSON | jq -r .current_condition[0].weatherDesc[0].value)
TEMP_CUR=$(echo $JSON | jq -r .current_condition[0].temp_F)
TEMP_FL=$(echo $JSON | jq -r .current_condition[0].FeelsLikeF)
TEMP_DELTA=$((TEMP_CUR-TEMP_FL))
TEMP_DELTA_ABS=${TEMP_DELTA#-}

if [ $TEMP_DELTA_ABS -gt 3 ]; then
  printf "%.0f°F / %.0f°F (%s)\n" $TEMP_CUR $TEMP_FL "$WX_DESC"
else
  printf "%.0f°F (%s)\n" $TEMP_CUR "$WX_DESC"
fi
