#!/bin/bash

if pidof xchat; then
  xchat --existing --command="set gui_tray 0"
  xchat --existing --command="gui apply"
  xchat --existing --command="set gui_tray 1"
  xchat --existing --command="gui apply"
fi

