#!/bin/bash

for ARG in "$@"; do
  if [[ $ARG == fx:* ]]; then
    /usr/bin/firefox "${ARG#fx:}"
    continue
  fi

  if [[ $ARG == irc:* ]]; then
    /usr/bin/xdg-open "ircs:${ARG#irc:}"
    continue
  fi

  /usr/bin/xdg-open "$ARG"
done
