#!/bin/bash

set -eo pipefail

CACHE_FILE=$XDG_CACHE_HOME/youtube-get-title.json
[ ! -e "$CACHE_FILE" ] && echo '{}' > "$CACHE_FILE"

URL=$1
[ -z $URL ] && exit 1

TITLE=$(jq -r ".\"$URL\" | select( . != null )" "$CACHE_FILE")

if [ -z "$TITLE" ]; then
  TITLE=$(yt-dlp --get-title $URL | iconv -f utf-8 -t ascii//translit)

  if [ -n "$TITLE" ]; then
    jq ".\"${URL}\" += \"${TITLE}\"" "$CACHE_FILE" | sponge "$CACHE_FILE"
  fi
fi

echo $TITLE
