#!/bin/bash

CACHE_FILE=$XDG_CACHE_HOME/youtube-title.json

URL=$1
[ -z $URL ] && exit 1

JSON=

if [ -e "$CACHE_FILE" ]; then
  JSON=$(cat "$CACHE_FILE")
fi

if [ -z "$JSON" ]; then
  JSON='{}'
fi

TITLE=$(echo "$JSON" | jq -r ".\"$URL\" | select( . != null )")

if [ -z "$TITLE" ]; then
  TITLE=$(youtube-dl --get-title $URL | tr -cd '[:print:]')

  if [ -n "$TITLE" ]; then
    UPDATED_JSON=$(echo "$JSON" | jq ".\"${URL}\" += \"${TITLE}\"")
    if [ -n "$UPDATED_JSON" ]; then
      echo "$UPDATED_JSON" > "$CACHE_FILE"
    fi
  fi
fi

echo $TITLE
