#!/bin/bash

CACHE_FILE=$XDG_CACHE_HOME/youtube-title.json

URL=$1
[ -z $URL ] && exit 1

JSON='{}'

if [ -e "$CACHE_FILE" ]; then
  JSON=$(cat "$CACHE_FILE")
fi

TITLE=$(echo $JSON | jq -r ".\"$URL\" | select( . != null )")

if [ -z "$TITLE" ]; then
  TITLE=$(youtube-dl --get-title $URL)

  if [ -n "$TITLE" ]; then
    echo $JSON | jq ".\"${URL}\" += \"${TITLE}\"" > "$CACHE_FILE"
  fi
fi

echo $TITLE
